export ThinStrongBeamSpec, GaussianStrongBeamSpec,
       ThinStrongBeam, GaussianStrongBeam,
       AbstractVirtualDrift, UnsafeVirtualDrift, HirataParaxialDrift,
       ChromaticDrift, ExactHamiltonianDrift,
       StrongTransverseMoments, transverse_covariance,
       gaussian_strong_beam_covariance, gaussian_beambeam_kick

abstract type ThinStrongBeamSpec{T} end
abstract type GaussianStrongBeamSpec{T} end

"""Strategy used for the canonical IP-to-collision-point virtual drift."""
abstract type AbstractVirtualDrift end

struct _ChromaticFrozenEnergyDrift <: AbstractVirtualDrift end

struct _ParaxialFrozenLongitudinalDrift <: AbstractVirtualDrift end

"""Original paraxial Hirata synchro-beam drift."""
struct HirataParaxialDrift <: AbstractVirtualDrift end

"""Virtual drift generated by `H = (px^2 + py^2) / (2(1 + pz))`."""
struct ChromaticDrift <: AbstractVirtualDrift end

"""Virtual drift generated by the exact field-free Hamiltonian."""
struct ExactHamiltonianDrift <: AbstractVirtualDrift end

const _VIRTUAL_DRIFT_TYPES = (
    hirata=HirataParaxialDrift,
    chromatic=ChromaticDrift,
    exact=ExactHamiltonianDrift,
)

const _UNSAFE_VIRTUAL_DRIFT_TYPES = (
    chromatic_frozen_energy=_ChromaticFrozenEnergyDrift,
    paraxial_frozen_longitudinal=_ParaxialFrozenLongitudinalDrift,
)
const _UnsafeVirtualDriftModel = Union{
    _ChromaticFrozenEnergyDrift,
    _ParaxialFrozenLongitudinalDrift,
}

"""
    UnsafeVirtualDrift(name)

Explicit access to non-symplectic diagnostic approximations. Supported names
are `:paraxial_frozen_longitudinal` and `:chromatic_frozen_energy`. These maps
must not be used for physical six-dimensional tracking.
"""
struct UnsafeVirtualDrift{D<:_UnsafeVirtualDriftModel} <: AbstractVirtualDrift
    model::D
end

function UnsafeVirtualDrift(name::Symbol)
    hasproperty(_UNSAFE_VIRTUAL_DRIFT_TYPES, name) || throw(ArgumentError(
        "unknown unsafe virtual drift :$name; expected one of " *
        "$(keys(_UNSAFE_VIRTUAL_DRIFT_TYPES))"))
    return UnsafeVirtualDrift(getproperty(_UNSAFE_VIRTUAL_DRIFT_TYPES, name)())
end

_virtual_drift(drift::AbstractVirtualDrift) = drift
function _virtual_drift(name::Symbol)
    hasproperty(_VIRTUAL_DRIFT_TYPES, name) || throw(ArgumentError(
        "unknown virtual_drift :$name; expected one of $(keys(_VIRTUAL_DRIFT_TYPES))"))
    return getproperty(_VIRTUAL_DRIFT_TYPES, name)()
end
_virtual_drift(value) = throw(ArgumentError(
    "virtual_drift must be a supported Symbol or AbstractVirtualDrift, got $(typeof(value))"))

"""
    StrongTransverseMoments

Compact, GPU-isbits representation of the strong slice covariance in local
coordinates `(x, px, y, py)`. The covariance is stored as the three blocks
`A = cov((x,y),(x,y))`, `B = cov((x,y),(px,py))`, and
`Q = cov((px,py),(px,py))`. The Boolean type parameter records whether
cross-plane coupling is present, allowing the uncoupled hot path to remain
compile-time specialized.
"""
struct StrongTransverseMoments{T,Coupled}
    a0::T
    b0::T
    d0::T
    bxx::T
    bxpy::T
    bypx::T
    bypy::T
    qxx::T
    qxy::T
    qyy::T
end

function transverse_covariance(m::StrongTransverseMoments{T}) where {T}
    covariance = zeros(T, 4, 4)
    covariance[1, 1] = m.a0
    covariance[1, 2] = covariance[2, 1] = m.bxx
    covariance[1, 3] = covariance[3, 1] = m.b0
    covariance[1, 4] = covariance[4, 1] = m.bxpy
    covariance[2, 2] = m.qxx
    covariance[2, 3] = covariance[3, 2] = m.bypx
    covariance[2, 4] = covariance[4, 2] = m.qxy
    covariance[3, 3] = m.d0
    covariance[3, 4] = covariance[4, 3] = m.bypy
    covariance[4, 4] = m.qyy
    return covariance
end

"""
    ThinStrongBeamSpec{T=Float64}(; kbb, klum=1, beta=nothing,
                                  alpha=(0,0), sigma=nothing,
                                  covariance=nothing, coupling=nothing,
                                  center=(0,0,0), angle=(0,0,0),
                                  curvature=(0,0,0), virtual_drift=:hirata,
                                  tracking_method=WeakStrongBeamBeamMap(),
                                  kwargs...)

Create an `ElementSpec{:thin_strong_beam}` for a weak-strong beam-beam
interaction. Supply either the legacy uncoupled `(beta, alpha, sigma)` data or
a symmetric `4 x 4` covariance in `(x, px, y, py)` order. `coupling` may be an
`XYCouplingSpec`, an `XYCoupling`, or a `4 x 4` linear matrix; it transforms
the uncoupled covariance before compilation.

`virtual_drift` selects **which Hamiltonian** the drift to and from the
collision point integrates. It is a physics-model choice, not a numerical
knob, so the default is the canonical published map rather than the most
accurate one:

- `:hirata` (default): `HirataParaxialDrift`, the exact flow of
  `(px^2 + py^2)/2`. This is Hirata's synchro-beam map as published and as
  assumed by cross-code comparisons. It has **no `pz` dependence**, hence no
  path lengthening at all.
- `:chromatic`: `ChromaticDrift`, the exact flow of `(px^2 + py^2)/2(1 + pz)`.
  Restores the leading chromatic term and path lengthening.
- `:exact`: `ExactHamiltonianDrift`, the full square root.

All three are exact flows of their own Hamiltonian, so all three are symplectic
and telescope exactly across slices. **The choice is a floor on accuracy that no
slice count removes.** Measured at EIC parameters with converged slicing
(`validation/gaussian_slicing_convergence.jl`), as a contribution to Furman's
`Q`:

    direction              |hirata - exact|   |chromatic - exact|
    electron on proton          2.9e-4              2.8e-8
    proton on electron          3.9e-5              1.4e-9

On the hadron side that puts the paraxial floor level with the slicing error at
`ns = 4`; past that, more slices refine a term that is no longer leading. Set
`virtual_drift = :chromatic` when the study needs accuracy below that floor --
it costs no `sqrt`, only `1/(1 + pz)`. Keep `:hirata` when reproducing published
synchro-beam results. See `docs/theory/gaussian_longitudinal_slicing.md`
Section 7.1.

Turn-dependent modulation is deliberately not part of this element. It belongs
in a scheduled task action, keeping the runtime element a compact description
of collision physics.
"""
ThinStrongBeamSpec(; kwargs...) = ThinStrongBeamSpec{Float64}(; kwargs...)
function (::Type{ThinStrongBeamSpec{T}})(; kbb,
                                        klum=one(T),
                                        beta=nothing,
                                        alpha=(zero(T), zero(T)),
                                        sigma=nothing,
                                        covariance=nothing,
                                        coupling=nothing,
                                        center=(zero(T), zero(T), zero(T)),
                                        angle=(zero(T), zero(T), zero(T)),
                                        curvature=(zero(T), zero(T), zero(T)),
                                        virtual_drift=:hirata,
                                        tracking_method=WeakStrongBeamBeamMap(),
                                        kwargs...) where {T}
    covariance4 = transverse_covariance(T;
        beta=beta, alpha=alpha, sigma=sigma,
        covariance=covariance, coupling=coupling)
    return ElementSpec{:thin_strong_beam}(
        _spec_params(;
            kbb=T(kbb),
            klum=T(klum),
            covariance=covariance4,
            center=_strong_tuple(center, 3, T),
            angle=_strong_tuple(angle, 3, T),
            curvature=_strong_tuple(curvature, 3, T),
            virtual_drift=_virtual_drift(virtual_drift),
            tracking_method=tracking_method,
            kwargs...,
        ),
    )
end

# `T<:Number` rather than `T<:AbstractFloat`: a dual number is `<:Real` and a
# truncated power series is `<:Number`, so the tighter bound refuses a parameter
# derivative outright. Float64 still satisfies it, so nothing else changes.
mutable struct ThinStrongBeam{M<:AbstractTrackingMethod,T<:Number,
                              P<:StrongTransverseMoments,D<:AbstractVirtualDrift} <: AbstractTrackOp
    method::M
    moments::P
    kbb::T
    klum::T
    xo::T
    yo::T
    zo::T
    pxo::T
    pyo::T
    pzo::T
    ppxo::T
    ppyo::T
    ppzo::T
    virtual_drift::D
    last_luminosity::T
end

function ThinStrongBeam(spec::ElementSpec{:thin_strong_beam},
                        method::AbstractTrackingMethod=tracking_method(spec))
    covariance4 = param(spec, :covariance)
    center = param(spec, :center)
    angle = param(spec, :angle)
    curvature = param(spec, :curvature)
    T = promote_type(map(typeof, (covariance4..., center..., angle..., curvature...,
                                  param(spec, :kbb), param(spec, :klum)))...)
    moments = _strong_transverse_moments(covariance4, T)
    return ThinStrongBeam(
        method,
        moments,
        T(param(spec, :kbb)),
        T(param(spec, :klum)),
        T(center[1]), T(center[2]), T(center[3]),
        T(angle[1]), T(angle[2]), T(angle[3]),
        T(curvature[1]), T(curvature[2]), T(curvature[3]),
        param(spec, :virtual_drift),
        zero(T),
    )
end

"""
    GaussianStrongBeamSpec{T=Float64}(; thin, ns, slice_center=nothing,
                                      slice_weight=nothing,
                                      slice_hoffset=nothing,
                                      slice_voffset=nothing,
                                      slice_pxoffset=nothing,
                                      slice_pyoffset=nothing,
                                      sigz=nothing,
                                      mean=nothing,
                                      covariance=nothing,
                                      slice_method=:sqrt_density,
                                      slice_width=nothing,
                                      hvoffset=nothing,
                                      tracking_method=WeakStrongBeamBeamMap(),
                                      kwargs...)

Create an `ElementSpec{:gaussian_strong_beam}`. `thin` may be a
`ThinStrongBeamSpec` or a compiled `ThinStrongBeam`.

When `covariance` is supplied it is the full `6 x 6` covariance in
`(x, px, y, py, z, pz)` order. Each thin longitudinal slice is constructed
from the conditional transverse Gaussian at its slice coordinate. Therefore
linear crab dispersion changes slice centroids, while momentum dispersion is
retained in the conditional within-slice covariance. `mean` defaults to the
centroid and angle stored in `thin`.

`slice_method` selects how the `ns` slice positions and weights are built from
the Gaussian line density. The `#n` labels are the algorithm numbers of Furman,
Zholents, Chen and Shatilov (LBL-37680, 1995):

- `:equal_area` (**#2**): equal-charge slices (`w = 1/ns`) with each
  kick at the point bisecting its slice's area,
  `z_k/sigz = sqrt(2) * erfinv(2k/ns)`.
- `:equal_area_centroid` (**#3**): same edges and weights, kick at the slice's
  centre of charge `ns * (phi(l_k) - phi(l_k+1))`. Same cost as `:equal_area`
  and strictly more accurate.
- `:sqrt_density` (**default**, **#4**): weights proportional to `sqrt(rho)`
  with centre-of-charge nodes, solved by fixed-point iteration. Furman's
  recommended rule and Xsuite's default (`TempSlicer(mode="shatilov")`). At EIC
  parameters it is 10.6x more accurate than `:equal_area` at `ns = 15` and 20x at
  `ns = 31`, for identical cost. **Changed from `:equal_area` on 2026-07-31**;
  pass `slice_method = :equal_area` explicitly to reproduce earlier results.
- `:min_cdf_area` (**#5**): minimises the area between the exact and
  discretized cumulative distributions.
- `:equal_spacing_density` (**#1**): uniform nodes with pointwise-density
  weights and the built-in half-span `1 + (ns-3)/12`.
- `:gauss_hermite`: Gauss-Hermite quadrature, exact for every moment through
  order `2*ns-1`. Not in Furman's set.
- `:equal_width`: uniform nodes `slice_width` apart, weighted by the exact
  integrated Gaussian charge of each bin, truncated at `+/- ns*slice_width/2`
  and renormalized. Related to #1 but not identical to it.

`slice_width` is consumed only by `:equal_width`. Supplying both `slice_center`
and `slice_weight` bypasses `slice_method` entirely and uses the given values.

Derivations, reference values, and the measured convergence ranking (the
equal-charge family is tail-limited to first order; `:gauss_hermite` and
`:sqrt_density` attack that) are in
`docs/theory/gaussian_longitudinal_slicing.md`.
"""
GaussianStrongBeamSpec(; kwargs...) = GaussianStrongBeamSpec{Float64}(; kwargs...)
function (::Type{GaussianStrongBeamSpec{T}})(; thin,
                                            ns,
                                            slice_center=nothing,
                                            slice_weight=nothing,
                                            slice_hoffset=nothing,
                                            slice_voffset=nothing,
                                            slice_pxoffset=nothing,
                                            slice_pyoffset=nothing,
                                            sigz=nothing,
                                            mean=nothing,
                                            covariance=nothing,
                                            slice_method=:sqrt_density,
                                            slice_width=nothing,
                                            hvoffset=nothing,
                                            tracking_method=WeakStrongBeamBeamMap(),
                                            kwargs...) where {T}
    return ElementSpec{:gaussian_strong_beam}(
        _spec_params(;
            thin=thin,
            ns=Int(ns),
            sigz=sigz === nothing ? nothing : T(sigz),
            slice_method=slice_method,
            slice_width=slice_width,
            slice_center=slice_center === nothing ? nothing : _strong_tuple(slice_center, Int(ns), T),
            slice_weight=slice_weight === nothing ? nothing : _strong_tuple(slice_weight, Int(ns), T),
            slice_hoffset=slice_hoffset === nothing ? nothing : _strong_tuple(slice_hoffset, Int(ns), T),
            slice_voffset=slice_voffset === nothing ? nothing : _strong_tuple(slice_voffset, Int(ns), T),
            slice_pxoffset=slice_pxoffset === nothing ? nothing : _strong_tuple(slice_pxoffset, Int(ns), T),
            slice_pyoffset=slice_pyoffset === nothing ? nothing : _strong_tuple(slice_pyoffset, Int(ns), T),
            mean=mean === nothing ? nothing : _strong_tuple(mean, 6, T),
            covariance=covariance === nothing ? nothing : _validated_covariance(covariance, 6, T),
            hvoffset=hvoffset,
            tracking_method=tracking_method,
            kwargs...,
        ),
    )
end

# `T<:Number` rather than `T<:AbstractFloat`: a dual number is `<:Real` and a
# truncated power series is `<:Number`, so the tighter bound refuses a parameter
# derivative outright. Float64 still satisfies it, so nothing else changes.
mutable struct GaussianStrongBeam{M<:AbstractTrackingMethod,T<:Number,
                                  P<:StrongTransverseMoments,
                                  D<:AbstractVirtualDrift,SliceAngles} <: AbstractTrackOp
    method::M
    ns::Int
    slice_center::Vector{T}
    slice_weight::Vector{T}
    slice_hoffset::Vector{T}
    slice_voffset::Vector{T}
    slice_pxoffset::Vector{T}
    slice_pyoffset::Vector{T}
    thin::ThinStrongBeam{M,T,P,D}
    last_luminosity::T
end

function GaussianStrongBeam(spec::ElementSpec{:gaussian_strong_beam},
                            method::AbstractTrackingMethod=tracking_method(spec))
    thin_raw = param(spec, :thin)
    thin = thin_raw isa ThinStrongBeam ? thin_raw : ThinStrongBeam(thin_raw, method)
    T0 = typeof(thin.kbb)
    covariance6 = getparam(spec, :covariance, nothing)
    crab_slope = ntuple(_ -> zero(T0), 4)
    if covariance6 !== nothing
        mean6 = getparam(spec, :mean, nothing)
        mean6 = mean6 === nothing ?
            (thin.xo, thin.pxo, thin.yo, thin.pyo, thin.zo, thin.pzo) :
            _strong_tuple(mean6, 6, T0)
        conditional4, crab_slope = _conditional_transverse_gaussian(covariance6, T0)
        thin = _thin_with_distribution(thin, conditional4, mean6)
    end
    sigz = getparam(spec, :sigz, nothing)
    if sigz === nothing && covariance6 !== nothing
        sigz = sqrt(T0(covariance6[5, 5]))
    end
    centers_tuple, weights_tuple = _gaussian_slices(
        T0,
        Int(param(spec, :ns)),
        getparam(spec, :slice_center, nothing),
        getparam(spec, :slice_weight, nothing),
        sigz,
        getparam(spec, :slice_method, :sqrt_density),
        getparam(spec, :slice_width, nothing),
    )
    hoff_tuple = getparam(spec, :slice_hoffset, nothing)
    voff_tuple = getparam(spec, :slice_voffset, nothing)
    pxoff_tuple = getparam(spec, :slice_pxoffset, nothing)
    pyoff_tuple = getparam(spec, :slice_pyoffset, nothing)
    hoff_tuple = hoff_tuple === nothing ? ntuple(_ -> zero(T0), Int(param(spec, :ns))) : _strong_tuple(hoff_tuple, Int(param(spec, :ns)), T0)
    voff_tuple = voff_tuple === nothing ? ntuple(_ -> zero(T0), Int(param(spec, :ns))) : _strong_tuple(voff_tuple, Int(param(spec, :ns)), T0)
    pxoff_tuple = pxoff_tuple === nothing ? ntuple(_ -> zero(T0), Int(param(spec, :ns))) : _strong_tuple(pxoff_tuple, Int(param(spec, :ns)), T0)
    pyoff_tuple = pyoff_tuple === nothing ? ntuple(_ -> zero(T0), Int(param(spec, :ns))) : _strong_tuple(pyoff_tuple, Int(param(spec, :ns)), T0)
    if covariance6 !== nothing
        hoff_tuple = ntuple(i -> hoff_tuple[i] + crab_slope[1] * centers_tuple[i], length(centers_tuple))
        pxoff_tuple = ntuple(i -> pxoff_tuple[i] + crab_slope[2] * centers_tuple[i], length(centers_tuple))
        voff_tuple = ntuple(i -> voff_tuple[i] + crab_slope[3] * centers_tuple[i], length(centers_tuple))
        pyoff_tuple = ntuple(i -> pyoff_tuple[i] + crab_slope[4] * centers_tuple[i], length(centers_tuple))
    end
    hvoffset = getparam(spec, :hvoffset, nothing)
    if hvoffset !== nothing
        dim = Symbol(get(hvoffset, :dim, :x))
        offsets = _crab_offsets(centers_tuple, T0(get(hvoffset, :coef, 0.0)),
                                T0(get(hvoffset, :frequency, -1.0)),
                                get(hvoffset, :harmonics, Dict(1 => 1.0)))
        if dim == :x
            hoff_tuple = ntuple(i -> hoff_tuple[i] + offsets[i], length(offsets))
        elseif dim == :y
            voff_tuple = ntuple(i -> voff_tuple[i] + offsets[i], length(offsets))
        else
            throw(ArgumentError("hvoffset dim must be :x or :y"))
        end
    end
    centers = collect(centers_tuple)
    weights = collect(weights_tuple)
    hoff = collect(hoff_tuple)
    voff = collect(voff_tuple)
    pxoff = collect(pxoff_tuple)
    pyoff = collect(pyoff_tuple)
    T = promote_type(map(typeof, (centers..., weights..., hoff..., voff..., pxoff..., pyoff...))...)
    slice_angles = any(!iszero, pxoff) || any(!iszero, pyoff)
    return GaussianStrongBeam{typeof(method),T,typeof(thin.moments),
                              typeof(thin.virtual_drift),slice_angles}(
        method, Int(param(spec, :ns)),
        T.(centers), T.(weights), T.(hoff), T.(voff),
        T.(pxoff), T.(pyoff), thin, zero(T))
end

@inline function track_particle(::WeakStrongBeamBeamMap, elem::ThinStrongBeam,
                                x, px, y, py, z, pz)
    x1, px1, y1, py1, z1, pz1, _ = _thin_strong_beam_track(elem, x, px, y, py, z, pz)
    return x1, px1, y1, py1, z1, pz1
end

@inline function track_particle(::WeakStrongBeamBeamMap, elem::GaussianStrongBeam,
                                x, px, y, py, z, pz)
    lum = zero(x + px + y + py + z + pz)
    kbb0 = elem.thin.kbb
    x0, y0, z0 = elem.thin.xo, elem.thin.yo, elem.thin.zo
    for i in elem.ns:-1:1
        slice_pxo, slice_pyo = _slice_transverse_angles(elem, i)
        thin = _slice_thin_strong_beam(elem.thin,
                                       kbb0 * elem.slice_weight[i],
                                       x0 + elem.slice_hoffset[i],
                                       y0 + elem.slice_voffset[i],
                                       z0 + elem.slice_center[i],
                                       slice_pxo, slice_pyo)
        x, px, y, py, z, pz, l = _thin_strong_beam_track(thin, x, px, y, py, z, pz)
        lum += l * elem.slice_weight[i]
    end
    return x, px, y, py, z, pz
end

@inline (elem::ThinStrongBeam)(x, px, y, py, z, pz) =
    track_particle(elem.method, elem, x, px, y, py, z, pz)
@inline (elem::GaussianStrongBeam)(x, px, y, py, z, pz) =
    track_particle(elem.method, elem, x, px, y, py, z, pz)

function _thin_strong_beam_track(elem::ThinStrongBeam, x, px, y, py, z, pz)
    (elem.moments.a0 == 0 || elem.moments.d0 == 0) && return x, px, y, py, z, pz, zero(x)
    x, px, y, py, z, pz, S = _thin_strong_forward_virtual_drift(elem, x, px, y, py, z, pz)
    x, px, y, py, z, pz, lum = _cp_kick(elem, S, x, px, y, py, z, pz)
    x, px, y, py, z, pz = _thin_strong_reverse_virtual_drift(elem, x, px, y, py, z, pz)
    return x, px, y, py, z, pz, lum * elem.klum
end

function _slice_thin_strong_beam(base::ThinStrongBeam{M,T}, kbb, xo, yo, zo,
                                 pxo=base.pxo, pyo=base.pyo) where {M,T}
    return ThinStrongBeam(
        base.method,
        base.moments,
        T(kbb), base.klum,
        T(xo), T(yo), T(zo),
        T(pxo), T(pyo), base.pzo,
        base.ppxo, base.ppyo, base.ppzo,
        base.virtual_drift,
        zero(T),
    )
end

@inline _thin_strong_forward_virtual_drift(elem::ThinStrongBeam, x, px, y, py, z, pz) =
    _forward_virtual_drift(elem.virtual_drift, x, px, y, py, z, pz, elem.zo)

@inline _thin_strong_reverse_virtual_drift(elem::ThinStrongBeam, x, px, y, py, z, pz) =
    _reverse_virtual_drift(elem.virtual_drift, x, px, y, py, z, pz, elem.zo)

@inline function _forward_virtual_drift(
        ::_ChromaticFrozenEnergyDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    phi = sqrt(1 - 0.5 * (px * px + py * py) / ((1 + pz) * (1 + pz))) - 1
    x += S * px / (1 + pz)
    y += S * py / (1 + pz)
    z += 2 * S * phi
    return x, px, y, py, z, pz, S
end

@inline function _reverse_virtual_drift(
        ::_ChromaticFrozenEnergyDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    psi = sqrt(1 + 0.5 * (px * px + py * py) / ((1 + pz) * (1 + pz))) - 1
    x -= S * px / (1 + pz)
    y -= S * py / (1 + pz)
    z += 2 * S * psi
    return x, px, y, py, z, pz
end

@inline function _forward_virtual_drift(
        ::_ParaxialFrozenLongitudinalDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    x += S * px
    y += S * py
    return x, px, y, py, z, pz, S
end

@inline function _reverse_virtual_drift(
        ::_ParaxialFrozenLongitudinalDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    x -= S * px
    y -= S * py
    return x, px, y, py, z, pz
end

@inline _forward_virtual_drift(
        drift::UnsafeVirtualDrift, x, px, y, py, z, pz, zo) =
    _forward_virtual_drift(drift.model, x, px, y, py, z, pz, zo)

@inline _reverse_virtual_drift(
        drift::UnsafeVirtualDrift, x, px, y, py, z, pz, zo) =
    _reverse_virtual_drift(drift.model, x, px, y, py, z, pz, zo)

@inline function _forward_virtual_drift(
        ::HirataParaxialDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    x += S * px
    y += S * py
    pz -= 0.25 * (px * px + py * py)
    return x, px, y, py, z, pz, S
end

@inline function _reverse_virtual_drift(
        ::HirataParaxialDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    x -= S * px
    y -= S * py
    pz += 0.25 * (px * px + py * py)
    return x, px, y, py, z, pz
end

@inline function _forward_virtual_drift(
        ::ChromaticDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    phi = sqrt(1 - 0.5 * (px * px + py * py) / ((1 + pz) * (1 + pz))) - 1
    x += S * px / (1 + pz)
    y += S * py / (1 + pz)
    z += 2 * S * phi
    pz += (1 + pz) * phi
    return x, px, y, py, z, pz, S
end

@inline function _reverse_virtual_drift(
        ::ChromaticDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    psi = sqrt(1 + 0.5 * (px * px + py * py) / ((1 + pz) * (1 + pz))) - 1
    x -= S * px / (1 + pz)
    y -= S * py / (1 + pz)
    z += 2 * S * psi
    pz += (1 + pz) * psi
    return x, px, y, py, z, pz
end

@inline function _forward_virtual_drift(
        ::ExactHamiltonianDrift, x, px, y, py, z, pz, zo)
    ps = sqrt((1 + pz) * (1 + pz) - px * px - py * py)
    H = 1 + pz - ps
    rr = 0.5 * H / ps
    z2 = (z + rr * zo) / (1 + rr)
    S = 0.5 * (z2 - zo)
    z -= H / ps * S
    pz -= 0.5 * H
    x += px / ps * S
    y += py / ps * S
    return x, px, y, py, z, pz, S
end

@inline function _reverse_virtual_drift(
        ::ExactHamiltonianDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    H0 = 0.5 * (px * px + py * py) / (1 + pz)
    ps0 = 1 + pz - 0.5 * H0
    pz += 0.5 * H0
    x -= px / ps0 * S
    y -= py / ps0 * S
    z += H0 / ps0 * S
    return x, px, y, py, z, pz
end

@inline function _cp_kick(elem::ThinStrongBeam, S, x, px, y, py, z, pz)
    xx = x - elem.xo + elem.pxo * S - 0.5 * elem.ppxo * S * S
    yy = y - elem.yo + elem.pyo * S - 0.5 * elem.ppyo * S * S
    px0, py0 = px, py
    x, px, y, py, z, pz, density = _cp_covariance_kick(
        elem.moments, elem.kbb, S, xx, yy, x, px, y, py, z, pz)
    centroid_u_x = elem.pxo - elem.ppxo * S
    centroid_u_y = elem.pyo - elem.ppyo * S
    pz += 0.5 * ((px - px0) * centroid_u_x + (py - py0) * centroid_u_y)
    return x, px, y, py, z, pz, density
end

@inline function _cp_covariance_kick(m::StrongTransverseMoments{T,false}, kbb,
                                     S, xx, yy, x, px, y, py, z, pz) where {T}
    a, _, d, au, _, du = _transport_transverse_moments(m, S)
    (a <= 0 || d <= 0) && return x, px, y, py, z, pz, zero(x)
    sigx, sigy = sqrt(a), sqrt(d)
    Kx, Ky, Hxx, Hyy =
        _gaussian_beambeam_kick_response(kbb, sigx, sigy, xx, yy)
    expterm = exp(-0.5 * (xx * xx / (sigx * sigx) + yy * yy / (sigy * sigy)))
    Fx, Fy = Kx * kbb, Ky * kbb
    px += Fx
    py += Fy
    pz += 0.25 * (Hxx * au + Hyy * du)
    return x, px, y, py, z, pz, expterm / TWOPI / sigx / sigy
end

@inline function _cp_covariance_kick(m::StrongTransverseMoments{T,true}, kbb,
                                     S, xx, yy, x, px, y, py, z, pz) where {T}
    a, b, d, au, bu, du = _transport_transverse_moments(m, S)
    detA = a * d - b * b
    (a <= 0 || d <= 0 || detA <= 0) && return x, px, y, py, z, pz, zero(x)
    adiff = a - d
    D = hypot(adiff, 2 * b)
    if D == zero(D)
        sigma = sqrt((a + d) / 2)
        Kx, Ky = gaussian_beambeam_kick(sigma, sigma, xx, yy)
        expterm = exp(-0.5 * (xx * xx + yy * yy) / (sigma * sigma))
        Fx, Fy = kbb * Kx, kbb * Ky
        Hxx, Hxy, Hyy = _round_gaussian_hessian(kbb, sigma, xx, yy, expterm)
        px += Fx
        py += Fy
        pz += 0.25 * (Hxx * au + 2 * Hxy * bu + Hyy * du)
        return x, px, y, py, z, pz, expterm / (TWOPI * sigma * sigma)
    end

    theta = 0.5 * atan(2 * b, a - d)
    c, s = cos(theta), sin(theta)
    lambda1 = (a + d + D) / 2
    lambda2 = (a + d - D) / 2
    sig1, sig2 = sqrt(lambda1), sqrt(lambda2)
    xh = c * xx + s * yy
    yh = -s * xx + c * yy
    eta = D / (a + d)
    inner, _ = _near_round_eta_bounds(eta)
    if eta <= inner
        Kxh, Kyh, H11, H22, L_over_D =
            _near_round_series_response(kbb, (a + d) / 2, eta, xh, yh)
    else
        Kxh, Kyh, H11, H22, L_over_D =
            _gaussian_beambeam_kick_response_principal(
                kbb, sig1, sig2, xh, yh)
    end
    expterm = exp(-0.5 * (xh * xh / lambda1 + yh * yh / lambda2))
    Fxh, Fyh = kbb * Kxh, kbb * Kyh
    Fx = c * Fxh - s * Fyh
    Fy = s * Fxh + c * Fyh
    px += Fx
    py += Fy

    Du = (adiff * (au - du) + 4 * b * bu) / D
    traceu = au + du
    pz += 0.125 * ((H11 + H22) * traceu + (H11 - H22) * Du)
    rotation_projection = (adiff * bu - b * (au - du)) / D
    pz -= 0.5 * kbb * rotation_projection * L_over_D
    return x, px, y, py, z, pz, expterm / (TWOPI * sig1 * sig2)
end

@inline function _transport_transverse_moments(m::StrongTransverseMoments, S)
    a = m.a0 - 2 * S * m.bxx + S * S * m.qxx
    b = m.b0 - S * (m.bxpy + m.bypx) + S * S * m.qxy
    d = m.d0 - 2 * S * m.bypy + S * S * m.qyy
    au = 2 * (m.bxx - S * m.qxx)
    bu = m.bxpy + m.bypx - 2 * S * m.qxy
    du = 2 * (m.bypy - S * m.qyy)
    return a, b, d, au, bu, du
end

@inline function _elliptic_gaussian_hessian_diagonal(kbb, sigx, sigy,
                                                       x, y, Kx, Ky, expterm)
    temp1 = kbb * (x * Kx + y * Ky)
    temp2 = sigx * sigx - sigy * sigy
    temp3 = sigy / sigx
    Hxx = (temp1 - 2 * kbb * (1 - expterm * temp3)) / temp2
    Hyy = (-temp1 + 2 * kbb * (1 - expterm / temp3)) / temp2
    return Hxx, Hyy
end

@inline function _round_gaussian_force_scale(r2, sigma2)
    u = r2 / (2 * sigma2)
    phi = u == zero(u) ? one(u) : -expm1(-u) / u
    return phi / sigma2
end

@inline function _round_gaussian_hessian(kbb, sigma, x, y, expterm)
    r2 = x * x + y * y
    sigma2 = sigma * sigma
    if r2 == 0
        h = -kbb / sigma2
        return h, zero(h), h
    end
    u = r2 / (2 * sigma2)
    if u < oftype(u, 1.0e-2)
        # For phi(u) = (1-exp(-u))/u, both phi and phi' need their series:
        # the direct phi' numerator cancels to second order as u approaches zero.
        oneu = one(u)
        phi = oneu + u * (
            -oneu / 2 + u * (
                oneu / 6 + u * (
                    -oneu / 24 + u * (
                        oneu / 120 + u * (
                            -oneu / 720 + u * (oneu / 5040)
                        )
                    )
                )
            )
        )
        dphi = -oneu / 2 + u * (
            oneu / 3 + u * (
                -oneu / 8 + u * (
                    oneu / 30 + u * (
                        -oneu / 144 + u * (
                            oneu / 840 - u * (oneu / 5760)
                        )
                    )
                )
            )
        )
        invsigma2 = inv(sigma2)
        f = phi * invsigma2
        fp = dphi * invsigma2 * invsigma2 / 2
    else
        one_minus_expterm = 1 - expterm
        f = 2 * one_minus_expterm / r2
        fp = 2 * (expterm * u - one_minus_expterm) / (r2 * r2)
    end
    Hxx = -kbb * (f + 2 * x * x * fp)
    Hxy = -kbb * (2 * x * y * fp)
    Hyy = -kbb * (f + 2 * y * y * fp)
    return Hxx, Hxy, Hyy
end

# The derivation, error balance, and validation procedure for these helpers are
# in docs/theory/near_round_bassetti_erskine_switch.md.  The outer boundary is
# eta_* = (8 C_BE(T) eps(T) / 3)^(1/4), obtained by balancing the leading
# covariance-response remainder (3/8)eta^3 against C_BE(T)eps(T)/eta.  The
# calibrated conditioning factor is sixty-four for Float64 and eight for
# Float32. The inner boundary starts a quintic potential-level blend at eta_*/2.
@inline _near_round_conditioning_factor(::Type{Float64}) = 64.0
@inline _near_round_conditioning_factor(::Type{Float32}) = 8.0f0
function _near_round_conditioning_factor(::Type{T}) where {T<:Real}
    throw(ArgumentError(
        "near-round Gaussian evaluation supports only Float32 and Float64; got $T"))
end

@inline function _near_round_eta_bounds(eta::T) where {T<:Real}
    conditioning = _near_round_conditioning_factor(T)
    outer = sqrt(sqrt((T(8) / T(3)) * conditioning * eps(T)))
    return outer / T(2), outer
end

@inline function _near_round_blend(eta::T) where {T<:Real}
    inner, outer = _near_round_eta_bounds(eta)
    if eta <= inner
        return zero(T), zero(T)
    elseif eta >= outer
        return one(T), zero(T)
    end
    invwidth = inv(outer - inner)
    t = (eta - inner) * invwidth
    w = t * t * t * (T(10) + t * (T(-15) + T(6) * t))
    dw = T(30) * t * t * (t - one(T)) * (t - one(T)) * invwidth
    return w, dw
end

@inline function _near_round_moments_0_6(q::T) where {T<:Real}
    if q <= T(2)
        m0 = zero(T)
        m1 = zero(T)
        m2 = zero(T)
        m3 = zero(T)
        m4 = zero(T)
        m5 = zero(T)
        m6 = zero(T)
        term = one(T)
        # Seventeen terms reach the Float32 rounding floor at q = 2; Float64
        # needs twenty-five. The type test is compile-time constant.
        last_order = T === Float32 ? 16 : 24
        for k in 0:last_order
            m0 += term / T(k + 1)
            m1 += term / T(k + 2)
            m2 += term / T(k + 3)
            m3 += term / T(k + 4)
            m4 += term / T(k + 5)
            m5 += term / T(k + 6)
            m6 += term / T(k + 7)
            term *= -q / T(k + 1)
        end
        return m0, m1, m2, m3, m4, m5, m6
    end
    eq = exp(-q)
    m0 = -expm1(-q) / q
    m1 = (m0 - eq) / q
    m2 = (T(2) * m1 - eq) / q
    m3 = (T(3) * m2 - eq) / q
    m4 = (T(4) * m3 - eq) / q
    m5 = (T(5) * m4 - eq) / q
    m6 = (T(6) * m5 - eq) / q
    return m0, m1, m2, m3, m4, m5, m6
end

@inline function _near_round_moments_3_11(q::T) where {T<:Real}
    if q <= T(2)
        m3 = zero(T)
        m4 = zero(T)
        m5 = zero(T)
        m6 = zero(T)
        m7 = zero(T)
        m8 = zero(T)
        m9 = zero(T)
        m10 = zero(T)
        m11 = zero(T)
        term = one(T)
        last_order = T === Float32 ? 16 : 24
        for k in 0:last_order
            m3 += term / T(k + 4)
            m4 += term / T(k + 5)
            m5 += term / T(k + 6)
            m6 += term / T(k + 7)
            m7 += term / T(k + 8)
            m8 += term / T(k + 9)
            m9 += term / T(k + 10)
            m10 += term / T(k + 11)
            m11 += term / T(k + 12)
            term *= -q / T(k + 1)
        end
        return m3, m4, m5, m6, m7, m8, m9, m10, m11
    end
    eq = exp(-q)
    m0 = -expm1(-q) / q
    m1 = (m0 - eq) / q
    m2 = (T(2) * m1 - eq) / q
    m3 = (T(3) * m2 - eq) / q
    m4 = (T(4) * m3 - eq) / q
    m5 = (T(5) * m4 - eq) / q
    m6 = (T(6) * m5 - eq) / q
    m7 = (T(7) * m6 - eq) / q
    m8 = (T(8) * m7 - eq) / q
    m9 = (T(9) * m8 - eq) / q
    m10 = (T(10) * m9 - eq) / q
    m11 = (T(11) * m10 - eq) / q
    return m3, m4, m5, m6, m7, m8, m9, m10, m11
end

@inline function _near_round_series_kick(v, eta, x, y)
    q = (x * x + y * y) / (2 * v)
    dr = (x * x - y * y) / (2 * v)
    m0, m1, m2, m3, m4, m5, m6 = _near_round_moments_0_6(q)
    eta2 = eta * eta
    eta3 = eta2 * eta
    c1x = dr * m2 - m1
    c1y = dr * m2 + m1
    T = typeof(q)
    c2x = T(1.5) * m2 + (-dr - q) * m3 + (dr * dr / T(2)) * m4
    c2y = T(1.5) * m2 + ( dr - q) * m3 + (dr * dr / T(2)) * m4
    c3x = -T(1.5) * m3 + (T(2.5) * dr + q) * m4 +
          (-dr * q - dr * dr / T(2)) * m5 + dr * dr * dr / T(6) * m6
    c3y =  T(1.5) * m3 + (T(2.5) * dr - q) * m4 +
          (-dr * q + dr * dr / T(2)) * m5 + dr * dr * dr / T(6) * m6
    return x / v * (m0 + eta * c1x + eta2 * c2x + eta3 * c3x),
           y / v * (m0 + eta * c1y + eta2 * c2y + eta3 * c3y)
end

@inline function _near_round_series_response(kbb, v, eta, x, y)
    T = typeof(v)
    q = (x * x + y * y) / (T(2) * v)
    dr = (x * x - y * y) / (T(2) * v)
    m0, m1, m2, m3, m4, m5, m6 = _near_round_moments_0_6(q)
    eta2 = eta * eta
    eta3 = eta2 * eta

    u1 = dr * m1
    u2 = m1 / T(2) - q * m2 + (dr * dr / T(2)) * m3
    u3 = T(1.5) * dr * m3 - dr * q * m4 + dr * dr * dr / T(6) * m5
    v1 = dr * (q * m2 - m1)
    v2 = T(1.5) * q * m2 - (q * q + dr * dr) * m3 +
         (q * dr * dr / T(2)) * m4
    v3 = -T(1.5) * dr * m3 + T(3.5) * dr * q * m4 -
         (dr * q * q + dr * dr * dr / T(2)) * m5 +
         dr * dr * dr * q / T(6) * m6

    c1x = dr * m2 - m1
    c1y = dr * m2 + m1
    c2x = T(1.5) * m2 + (-dr - q) * m3 + (dr * dr / T(2)) * m4
    c2y = T(1.5) * m2 + ( dr - q) * m3 + (dr * dr / T(2)) * m4
    c3x = -T(1.5) * m3 + (T(2.5) * dr + q) * m4 +
          (-dr * q - dr * dr / T(2)) * m5 + dr * dr * dr / T(6) * m6
    c3y =  T(1.5) * m3 + (T(2.5) * dr - q) * m4 +
          (-dr * q + dr * dr / T(2)) * m5 + dr * dr * dr / T(6) * m6
    Kx = x / v * (m0 + eta * c1x + eta2 * c2x + eta3 * c3x)
    Ky = y / v * (m0 + eta * c1y + eta2 * c2y + eta3 * c3y)

    uv = -exp(-q) + eta * v1 + eta2 * v2 + eta3 * v3
    ueta = u1 + T(2) * eta * u2 + T(3) * eta2 * u3
    H1 = kbb / v * (uv + (one(T) - eta) * ueta)
    H2 = kbb / v * (uv - (one(T) + eta) * ueta)
    L_over_D = -x * y / (v * v) * (
        m1 + eta * dr * m3 +
        eta2 * (T(1.5) * m3 - q * m4 + dr * dr / T(2) * m5))
    return Kx, Ky, H1, H2, L_over_D
end

# U_exact - U_series through eta^6.  Only the blend chain term needs this
# gauge-independent residual; eta^7 is below the balanced transition error for
# both Float32 and Float64 over the validated field domain.
@inline function _near_round_potential_residual(v, eta, x, y)
    T = typeof(v)
    q = (x * x + y * y) / (T(2) * v)
    dr = (x * x - y * y) / (T(2) * v)
    m3, m4, m5, m6, m7, m8, m9, m10, m11 =
        _near_round_moments_3_11(q)
    dr2 = dr * dr
    q2 = q * q
    u4 = T(3) / T(8) * m3 - T(1.5) * q * m4 +
         (T(5) * dr2 + T(2) * q2) / T(4) * m5 -
         dr2 * q / T(2) * m6 + dr2 * dr2 / T(24) * m7
    u5 = T(15) / T(8) * dr * m5 - T(2.5) * dr * q * m6 +
         dr * (T(7) * dr2 + T(6) * q2) / T(12) * m7 -
         dr * dr2 * q / T(6) * m8 + dr * dr2 * dr2 / T(120) * m9
    u6 = T(5) / T(16) * m5 - T(15) / T(8) * q * m6 +
         T(5) * (T(7) * dr2 + T(4) * q2) / T(16) * m7 -
         q * (T(21) * dr2 + T(2) * q2) / T(12) * m8 +
         dr2 * (T(3) * dr2 + T(4) * q2) / T(16) * m9 -
         dr2 * dr2 * q / T(24) * m10 +
         dr2 * dr2 * dr2 / T(720) * m11
    return eta * eta * eta * eta * (u4 + eta * (u5 + eta * u6))
end

@inline function _use_elliptic_near_axis(sig1, sig2, x, y, eta)
    T = typeof(sig1)
    rho2 = x * x / (sig1 * sig1) + y * y / (sig2 * sig2)
    # The fifth-degree radial series has O(rho^6) relative truncation error,
    # while Faddeeva subtraction has O(eps/(rho*sqrt(eta))) relative error.
    # Compare rho^7 directly to avoid a fractional power in GPU kernels.
    return rho2 * rho2 * rho2 * sqrt(rho2) <= eps(T) / sqrt(eta)
end

@inline function _elliptic_gaussian_axis_component(
        kbb, sigx, sigy, x, y)
    T = typeof(sigx)
    s = sigx + sigy
    sx2 = sigx * sigx
    sx3 = sx2 * sigx
    sx5 = sx3 * sx2
    sy2 = sigy * sigy
    sy3 = sy2 * sigy
    s2 = s * s
    s3 = s2 * s

    j00 = T(2) / (sigx * s)
    j10 = T(2) * (T(2) * sigx + sigy) / (T(3) * sx3 * s2)
    j01 = T(2) / (sigx * sigy * s2)
    j20 = T(2) * (T(8) * sx2 + T(9) * sigx * sigy + T(3) * sy2) /
          (T(15) * sx5 * s3)
    j11 = T(2) * (T(3) * sigx + sigy) /
          (T(3) * sx3 * sigy * s3)
    j02 = T(2) * (sigx + T(3) * sigy) /
          (T(3) * sigx * sy3 * s3)

    x2 = x * x
    y2 = y * y
    x4 = x2 * x2
    y4 = y2 * y2
    x2y2 = x2 * y2
    scale = j00 - (x2 * j10 + y2 * j01) / T(2) +
            x4 * j20 / T(8) + x2y2 * j11 / T(4) + y4 * j02 / T(8)
    derivative = j00 - T(1.5) * x2 * j10 - y2 * j01 / T(2) +
                 T(0.625) * x4 * j20 + T(0.75) * x2y2 * j11 +
                 y4 * j02 / T(8)
    return x * scale, -kbb * derivative
end

@inline function _elliptic_gaussian_near_axis_response(
        kbb, sig1, sig2, x, y)
    Kx, H1 = _elliptic_gaussian_axis_component(kbb, sig1, sig2, x, y)
    Ky, H2 = _elliptic_gaussian_axis_component(kbb, sig2, sig1, y, x)
    return Kx, Ky, H1, H2
end

@inline function _elliptic_gaussian_kick_principal(sig1, sig2, x, y)
    T = typeof(sig1)
    v = (sig1 * sig1 + sig2 * sig2) / 2
    eta = (sig1 * sig1 - sig2 * sig2) / (2 * v)
    if _use_elliptic_near_axis(sig1, sig2, x, y, eta)
        Kx, Ky, _, _ = _elliptic_gaussian_near_axis_response(
            zero(sig1), sig1, sig2, x, y)
        return Kx, Ky
    end
    negx = x < 0
    negy = y < 0
    x = abs(x)
    y = abs(y)
    denominator = T(SQRT2) * sqrt(sig1 * sig1 - sig2 * sig2)
    z1 = complex(x / denominator, y / denominator)
    z2 = complex(sig2 / sig1 * x / denominator, sig1 / sig2 * y / denominator)
    A = T(2) * T(SQRTPI) / denominator
    B = exp(-x * x / (2 * sig1 * sig1) - y * y / (2 * sig2 * sig2))
    ret = A * (faddeeva_w(z1) - B * faddeeva_w(z2))
    Kx = imag(ret)
    Ky = real(ret)
    return negx ? -Kx : Kx, negy ? -Ky : Ky
end

@inline function _gaussian_beambeam_kick_principal(sig1, sig2, x, y)
    v = (sig1 * sig1 + sig2 * sig2) / 2
    eta = (sig1 * sig1 - sig2 * sig2) / (2 * v)
    if eta == zero(eta)
        r2 = x * x + y * y
        scale = _round_gaussian_force_scale(r2, v)
        return scale * x, scale * y
    end
    inner, outer = _near_round_eta_bounds(eta)
    if eta <= inner
        return _near_round_series_kick(v, eta, x, y)
    end
    Kex, Key = _elliptic_gaussian_kick_principal(sig1, sig2, x, y)
    if eta >= outer
        return Kex, Key
    end
    w, _ = _near_round_blend(eta)
    Ksx, Ksy = _near_round_series_kick(v, eta, x, y)
    return Ksx + w * (Kex - Ksx), Ksy + w * (Key - Ksy)
end

@inline function _gaussian_beambeam_kick_response_principal(
        kbb, sig1, sig2, x, y)
    T = typeof(sig1)
    v = (sig1 * sig1 + sig2 * sig2) / T(2)
    eta = (sig1 * sig1 - sig2 * sig2) / (T(2) * v)
    if eta == zero(eta)
        r2 = x * x + y * y
        scale = _round_gaussian_force_scale(r2, v)
        expterm = exp(-r2 / (T(2) * v))
        H1, _, H2 = _round_gaussian_hessian(kbb, sqrt(v), x, y, expterm)
        return scale * x, scale * y, H1, H2, zero(T)
    end

    inner, outer = _near_round_eta_bounds(eta)
    if eta <= inner
        return _near_round_series_response(kbb, v, eta, x, y)
    end

    Kex, Key = _elliptic_gaussian_kick_principal(sig1, sig2, x, y)
    expterm = exp(-T(0.5) * (x * x / (sig1 * sig1) + y * y / (sig2 * sig2)))
    if _use_elliptic_near_axis(sig1, sig2, x, y, eta)
        _, _, He1, He2 = _elliptic_gaussian_near_axis_response(
            kbb, sig1, sig2, x, y)
    else
        He1, He2 = _elliptic_gaussian_hessian_diagonal(
            kbb, sig1, sig2, x, y, Kex, Key, expterm)
    end
    D = T(2) * v * eta
    Le_over_D = (Kex * y - Key * x) / D
    if eta >= outer
        return Kex, Key, He1, He2, Le_over_D
    end

    w, dw = _near_round_blend(eta)
    Ksx, Ksy, Hs1, Hs2, Ls_over_D =
        _near_round_series_response(kbb, v, eta, x, y)
    deltaU = _near_round_potential_residual(v, eta, x, y)
    chain = kbb * dw * deltaU / v
    Kx = Ksx + w * (Kex - Ksx)
    Ky = Ksy + w * (Key - Ksy)
    H1 = Hs1 + w * (He1 - Hs1) + (one(T) - eta) * chain
    H2 = Hs2 + w * (He2 - Hs2) - (one(T) + eta) * chain
    L_over_D = Ls_over_D + w * (Le_over_D - Ls_over_D)
    return Kx, Ky, H1, H2, L_over_D
end

@inline function _gaussian_beambeam_kick_response(kbb, sigx, sigy, x, y)
    if sigx >= sigy
        Kx, Ky, Hx, Hy, _ = _gaussian_beambeam_kick_response_principal(
            kbb, sigx, sigy, x, y)
    else
        Ky, Kx, Hy, Hx, _ = _gaussian_beambeam_kick_response_principal(
            kbb, sigy, sigx, y, x)
    end
    return Kx, Ky, Hx, Hy
end

function gaussian_beambeam_kick(sigx, sigy, x, y)
    (sigx == 0 || sigy == 0) && return zero(x), zero(y)
    if sigx >= sigy
        return _gaussian_beambeam_kick_principal(sigx, sigy, x, y)
    end
    Ky, Kx = _gaussian_beambeam_kick_principal(sigy, sigx, y, x)
    return Kx, Ky
end

"""
    transverse_covariance([T=Float64]; beta, alpha=(0,0), sigma,
                           covariance=nothing, coupling=nothing)

Return the strong-slice `4 x 4` covariance in `(x, px, y, py)` order.
Either provide `covariance` directly, or provide uncoupled Twiss data. An
optional `coupling` linear map is applied as `M * covariance * M'`.
"""
transverse_covariance(; kwargs...) = transverse_covariance(Float64; kwargs...)
function transverse_covariance(::Type{T}; beta=nothing,
                               alpha=(zero(T), zero(T)), sigma=nothing,
                               covariance=nothing, coupling=nothing) where {T}
    if covariance === nothing
        beta === nothing && throw(ArgumentError(
            "ThinStrongBeamSpec requires beta and sigma, or a 4 x 4 covariance"))
        sigma === nothing && throw(ArgumentError(
            "ThinStrongBeamSpec requires beta and sigma, or a 4 x 4 covariance"))
        beta2 = _strong_tuple(beta, 2, T)
        alpha2 = _strong_tuple(alpha, 2, T)
        sigma2 = _strong_tuple(sigma, 2, T)
        all(>(zero(T)), beta2) || throw(ArgumentError("strong-beam beta functions must be positive"))
        all(>(zero(T)), sigma2) || throw(ArgumentError("strong-beam transverse sizes must be positive"))
        cov4 = zeros(T, 4, 4)
        for (i, q, p) in ((1, 1, 2), (2, 3, 4))
            emit = sigma2[i] * sigma2[i] / beta2[i]
            gamma = (one(T) + alpha2[i] * alpha2[i]) / beta2[i]
            cov4[q, q] = sigma2[i] * sigma2[i]
            cov4[q, p] = cov4[p, q] = -emit * alpha2[i]
            cov4[p, p] = emit * gamma
        end
    else
        beta === nothing || throw(ArgumentError("beta/sigma and covariance are alternative strong-beam descriptions"))
        sigma === nothing || throw(ArgumentError("beta/sigma and covariance are alternative strong-beam descriptions"))
        coupling === nothing || throw(ArgumentError("apply coupling before supplying an explicit covariance"))
        return _validated_covariance(covariance, 4, T)
    end
    if coupling !== nothing
        matrix = _xy_coupling_matrix(coupling, T)
        cov4 = matrix * cov4 * transpose(matrix)
    end
    return _validated_covariance(cov4, 4, T)
end

"""
    gaussian_strong_beam_covariance(transverse, longitudinal;
                                    crab_dispersion=(0,0,0,0),
                                    momentum_dispersion=(0,0,0,0))

Construct a `6 x 6` Gaussian covariance in `(x, px, y, py, z, pz)` order from
an intrinsic transverse covariance, a `2 x 2` longitudinal covariance, and
linear relations `w = w_beta + crab_dispersion*z + momentum_dispersion*pz`.
"""
function gaussian_strong_beam_covariance(transverse, longitudinal;
        crab_dispersion=(0, 0, 0, 0), momentum_dispersion=(0, 0, 0, 0))
    T = promote_type(eltype(transverse), eltype(longitudinal),
                     map(typeof, (crab_dispersion..., momentum_dispersion...))...)
    transverse4 = _validated_covariance(transverse, 4, T)
    longitudinal2 = _validated_covariance(longitudinal, 2, T)
    zeta = collect(_strong_tuple(crab_dispersion, 4, T))
    eta = collect(_strong_tuple(momentum_dispersion, 4, T))
    dispersion = hcat(zeta, eta)
    cov6 = zeros(T, 6, 6)
    cov6[1:4, 1:4] .= transverse4 .+ dispersion * longitudinal2 * transpose(dispersion)
    cov6[1:4, 5:6] .= dispersion * longitudinal2
    cov6[5:6, 1:4] .= transpose(cov6[1:4, 5:6])
    cov6[5:6, 5:6] .= longitudinal2
    return _validated_covariance(cov6, 6, T)
end

function _validated_covariance(covariance, n::Int, ::Type{T}) where {T}
    size(covariance) == (n, n) || throw(ArgumentError("expected a $n x $n covariance"))
    cov = Matrix{T}(covariance)
    all(isfinite, cov) || throw(ArgumentError("covariance entries must be finite"))
    scale = maximum(abs, cov)
    symmetry_tolerance = T(100) * eps(T) * max(scale, one(T))
    maximum(abs, cov - transpose(cov)) <= symmetry_tolerance ||
        throw(ArgumentError("covariance must be symmetric"))
    cov = (cov + transpose(cov)) / 2
    psd_tolerance = T(100) * eps(T) * max(scale, eps(T))
    minimum(eigvals(Symmetric(cov))) >= -psd_tolerance ||
        throw(ArgumentError("covariance must be positive semidefinite"))
    return cov
end

function _xy_coupling_matrix(coupling, ::Type{T}) where {T}
    if coupling isa AbstractMatrix
        matrix = Matrix{T}(coupling)
    else
        runtime = coupling isa ElementSpec{:xy_coupling} ? XYCoupling(coupling) : coupling
        runtime isa XYCoupling || throw(ArgumentError(
            "coupling must be an XYCouplingSpec, XYCoupling, or 4 x 4 matrix"))
        matrix = zeros(T, 4, 4)
        for column in 1:4
            input = ntuple(i -> i == column ? one(T) : zero(T), 4)
            output = track_particle(runtime.method, runtime, input[1], input[2],
                                    input[3], input[4], zero(T), zero(T))
            matrix[:, column] .= output[1:4]
        end
    end
    size(matrix) == (4, 4) || throw(ArgumentError("coupling matrix must be 4 x 4"))
    all(isfinite, matrix) || throw(ArgumentError("coupling matrix entries must be finite"))
    J = T[0 1 0 0; -1 0 0 0; 0 0 0 1; 0 0 -1 0]
    residual = transpose(matrix) * J * matrix - J
    tolerance = T(500) * eps(T) * max(opnorm(matrix)^2, one(T))
    opnorm(residual, Inf) <= tolerance || throw(ArgumentError("coupling matrix must be symplectic"))
    return matrix
end

function _strong_transverse_moments(covariance4, ::Type{T}) where {T}
    cov = _validated_covariance(covariance4, 4, T)
    coupled = !(iszero(cov[1, 3]) && iszero(cov[1, 4]) &&
                iszero(cov[2, 3]) && iszero(cov[2, 4]))
    return StrongTransverseMoments{T,coupled}(
        cov[1, 1], cov[1, 3], cov[3, 3],
        cov[1, 2], cov[1, 4], cov[3, 2], cov[3, 4],
        cov[2, 2], cov[2, 4], cov[4, 4])
end

function _conditional_transverse_gaussian(covariance6, ::Type{T}) where {T}
    cov = _validated_covariance(covariance6, 6, T)
    variance_z = cov[5, 5]
    variance_z > zero(T) || throw(ArgumentError(
        "a sliced 6D Gaussian requires positive longitudinal position variance"))
    wz = cov[1:4, 5]
    slope = Tuple(wz ./ variance_z)
    conditional = cov[1:4, 1:4] - wz * transpose(wz) / variance_z
    return _validated_covariance(conditional, 4, T), slope
end

function _thin_with_distribution(base::ThinStrongBeam{M,T}, covariance4, mean6) where {M,T}
    moments = _strong_transverse_moments(covariance4, T)
    return ThinStrongBeam(
        base.method, moments, base.kbb, base.klum,
        T(mean6[1]), T(mean6[3]), T(mean6[5]),
        T(mean6[2]), T(mean6[4]), T(mean6[6]),
        base.ppxo, base.ppyo, base.ppzo,
        base.virtual_drift, zero(T))
end

"""
Longitudinal slicing rules for a frozen Gaussian source bunch.

Each entry maps a public `slice_method` value to the prescription it implements.
Derivations, reference values, and the measured convergence ranking are in
`docs/theory/gaussian_longitudinal_slicing.md`; the `#n` labels are the
algorithm numbers of Furman, Zholents, Chen and Shatilov (LBL-37680, 1995).
"""
const SLICE_METHODS = (:equal_area, :equal_width, :equal_area_centroid,
                       :sqrt_density, :gauss_hermite, :equal_spacing_density,
                       :min_cdf_area)

function _gaussian_slices(::Type{T}, ns::Int, slice_center, slice_weight, sigz, method, width) where {T}
    if slice_center !== nothing && slice_weight !== nothing
        return _strong_tuple(slice_center, ns, T), _strong_tuple(slice_weight, ns, T)
    end
    sigz === nothing && throw(ArgumentError("GaussianStrongBeamSpec requires sigz unless slice_center and slice_weight are supplied"))
    ns > 0 || throw(ArgumentError("ns must be positive, got $ns"))
    T(sigz) > zero(T) || throw(ArgumentError("sigz must be positive, got $sigz"))
    method == :equal_area && return _equal_area_slices(T, ns, T(sigz))
    method == :equal_width && return _equal_width_slices(T, ns, T(sigz), T(width))
    method == :equal_area_centroid && return _equal_area_centroid_slices(T, ns, T(sigz))
    method == :sqrt_density && return _sqrt_density_slices(T, ns, T(sigz))
    method == :gauss_hermite && return _gauss_hermite_slices(T, ns, T(sigz))
    method == :equal_spacing_density && return _equal_spacing_density_slices(T, ns, T(sigz))
    method == :min_cdf_area && return _min_cdf_area_slices(T, ns, T(sigz))
    throw(ArgumentError("unknown slice_method $(repr(method)); expected one of $(SLICE_METHODS)"))
end

# Standard-normal helpers shared by the slicing rules. Nodes are built in units
# of sigma_z and scaled once at the end.
@inline _snorm_pdf(x::T) where {T} = exp(-x * x / 2) / T(SQRT2PI)
@inline _snorm_cdf(x::T) where {T} = (one(T) + erf(x / T(SQRT2))) / 2
@inline _snorm_quantile(p::T) where {T} = T(SQRT2) * inverse_erf(2p - one(T))
@inline _snorm_pdf_at(x::T) where {T} = isinf(x) ? zero(T) : _snorm_pdf(x)

# Equal-charge slice edges: bin j spans cumulative [(j-1)/ns, j/ns].
@inline function _equal_charge_edge(::Type{T}, j::Int, ns::Int) where {T}
    j <= 0 && return T(-Inf)
    j >= ns && return T(Inf)
    return _snorm_quantile(T(j) / T(ns))
end

"""
Furman algorithm #3: equal-charge slices with the kick at each slice's centre of
charge, `z_k/sigz = ns * (phi(l_k) - phi(l_k+1))`. Same edges and weights as
`:equal_area`; only the node differs, and the conditional mean is preserved.
"""
function _equal_area_centroid_slices(::Type{T}, ns::Int, sigz::T) where {T}
    weights = fill(inv(T(ns)), ns)
    centers = Vector{T}(undef, ns)
    for j in 1:ns
        a = _equal_charge_edge(T, j - 1, ns)
        b = _equal_charge_edge(T, j, ns)
        centers[j] = sigz * T(ns) * (_snorm_pdf_at(a) - _snorm_pdf_at(b))
    end
    return Tuple(centers), Tuple(weights)
end

"""
Furman algorithm #4: weights proportional to `sqrt(rho)` with centre-of-charge
nodes, the edges chosen so slice `k` carries exactly `w_k`. The node and weight
relations are mutually coupled and solved by fixed-point iteration from equal
charge. This is the rule Furman recommends and the one Xsuite's
`TempSlicer(mode="shatilov")` implements.
"""
function _sqrt_density_slices(::Type{T}, ns::Int, sigz::T;
                              iters::Int=500, tol::Real=eps(T)) where {T}
    ns == 1 && return (zero(T),), (one(T),)
    w = fill(inv(T(ns)), ns)
    centers = zeros(T, ns)
    edges = Vector{T}(undef, ns + 1)
    for _ in 1:iters
        edges[1] = T(-Inf)
        edges[ns + 1] = T(Inf)
        cum = zero(T)
        for j in 1:(ns - 1)
            cum += w[j]
            edges[j + 1] = _snorm_quantile(clamp(cum, eps(T), one(T) - eps(T)))
        end
        for j in 1:ns
            centers[j] = (_snorm_pdf_at(edges[j]) - _snorm_pdf_at(edges[j + 1])) / w[j]
        end
        total = zero(T)
        change = zero(T)
        for j in 1:ns
            wj = sqrt(_snorm_pdf(centers[j]))
            change = max(change, abs(wj - w[j]))
            w[j] = wj
            total += wj
        end
        w ./= total
        change / total <= tol && break
    end
    return Tuple(centers .* sigz), Tuple(w)
end

"""
Gauss-Hermite quadrature (not in Furman's set): nodes at the roots of the
probabilists' Hermite polynomial `He_ns`, obtained without root finding by the
Golub-Welsch construction. Reproduces every moment through order `2*ns-1`
exactly, so it is the only rule here that preserves `sigz` itself.
"""
function _gauss_hermite_slices(::Type{T}, ns::Int, sigz::T) where {T}
    ns == 1 && return (zero(T),), (one(T),)
    # Solve in Float64 for conditioning, then convert.
    jacobi = SymTridiagonal(zeros(Float64, ns), [sqrt(Float64(k)) for k in 1:(ns - 1)])
    decomposition = eigen(jacobi)
    nodes = decomposition.values
    weights = abs2.(decomposition.vectors[1, :])
    weights ./= sum(weights)
    order = sortperm(nodes)
    return Tuple(T(sigz * nodes[i]) for i in order), Tuple(T(weights[i]) for i in order)
end

"""
Furman algorithm #1: uniformly spaced nodes with weights sampled from the
density *at the node*, `z_L/sigz = 1 + (ns-3)/12`. The half-span is part of the
rule and grows linearly with `ns`, so this carries its own truncation policy.
Distinct from `:equal_width`, which integrates the charge of each bin instead.
"""
function _equal_spacing_density_slices(::Type{T}, ns::Int, sigz::T) where {T}
    ns == 1 && return (zero(T),), (one(T),)
    span = one(T) + (T(ns) - 3) / 12
    centers = Vector{T}(undef, ns)
    weights = Vector{T}(undef, ns)
    total = zero(T)
    for j in 1:ns
        scaled = span * T(2j - ns - 1) / T(ns - 1)
        centers[j] = sigz * scaled
        weights[j] = _snorm_pdf(scaled)
        total += weights[j]
    end
    weights ./= total
    return Tuple(centers), Tuple(weights)
end

"""
Furman algorithm #5: minimise the area enclosed between the exact and
discretized cumulative distributions. Both stationarity conditions are closed
form — each node sits at the cumulative midpoint of its own jump, and each
level crosses the exact CDF at the arithmetic midpoint of its interval — so the
rule reduces to a fixed-point iteration rather than the optimizer Ref. [1]
describes.
"""
function _min_cdf_area_slices(::Type{T}, ns::Int, sigz::T;
                              iters::Int=500, tol::Real=eps(T)) where {T}
    ns == 1 && return (zero(T),), (one(T),)
    half = ns ÷ 2
    odd = isodd(ns)
    # Start from algorithm #2 (parity-aware equal-charge medians).
    nodes = [_snorm_quantile(T(0.5) + (odd ? T(k) / T(ns) : T(2k - 1) / T(2ns)))
             for k in 1:half]
    levels = zeros(T, half + 1)
    for _ in 1:iters
        levels[1] = odd ? _snorm_cdf(nodes[1] / 2) - T(0.5) : zero(T)
        for k in 1:(half - 1)
            levels[k + 1] = _snorm_cdf((nodes[k] + nodes[k + 1]) / 2) - T(0.5)
        end
        levels[half + 1] = T(0.5)
        change = zero(T)
        for k in 1:half
            updated = _snorm_quantile(T(0.5) + (levels[k] + levels[k + 1]) / 2)
            change = max(change, abs(updated - nodes[k]))
            nodes[k] = updated
        end
        change <= tol && break
    end
    weights = [levels[k + 1] - levels[k] for k in 1:half]
    centers = odd ? vcat(-reverse(nodes), zero(T), nodes) : vcat(-reverse(nodes), nodes)
    allweights = odd ? vcat(reverse(weights), 2 * levels[1], weights) :
                       vcat(reverse(weights), weights)
    return Tuple(centers .* sigz), Tuple(allweights)
end

function _equal_area_slices(::Type{T}, ns::Int, sigz::T) where {T}
    centers = zeros(T, ns)
    weights = fill(inv(T(ns)), ns)
    rr = SQRT2 * sigz
    if isodd(ns)
        w = (ns - 1) ÷ 2
        centers[w + 1] = zero(T)
        for i in 1:w
            centers[i + w + 1] = inverse_erf(2 * i / ns) * rr
            centers[-i + w + 1] = -centers[i + w + 1]
        end
    else
        w = ns ÷ 2
        for i in 1:w
            centers[i + w] = inverse_erf((2 * i - 1) / ns) * rr
            centers[-i + w + 1] = -centers[i + w]
        end
    end
    return Tuple(centers), Tuple(weights)
end

function _equal_width_slices(::Type{T}, ns::Int, sigz::T, width::T) where {T}
    centers = zeros(T, ns)
    weights = zeros(T, ns)
    nw = width / SQRT2 / sigz
    sumw = erf(nw * ns / 2)
    if isodd(ns)
        w = (ns - 1) ÷ 2
        upper = erf(0.5 * nw)
        weights[w + 1] = upper / sumw
        for i in 1:w
            centers[i + w + 1] = width * i
            centers[-i + w + 1] = -centers[i + w + 1]
            lower = upper
            upper = erf((i + 0.5) * nw)
            weights[i + w + 1] = (upper - lower) / 2 / sumw
            weights[-i + w + 1] = weights[i + w + 1]
        end
    else
        w = ns ÷ 2
        upper = zero(T)
        for i in 1:w
            centers[i + w] = (i - 0.5) * width
            centers[-i + w + 1] = -centers[i + w]
            lower = upper
            upper = erf(i * nw)
            weights[i + w] = (upper - lower) / 2 / sumw
            weights[-i + w + 1] = weights[i + w]
        end
    end
    return Tuple(centers), Tuple(weights)
end

function _crab_offsets(centers, coef, freq, harmonics)
    freq <= 0 && return ntuple(_ -> zero(coef), length(centers))
    kcc = TWOPI * freq / CLIGHT
    return ntuple(length(centers)) do i
        t = -centers[i]
        for (h, rel) in pairs(harmonics)
            t += rel * sin(h * kcc * centers[i]) / (h * kcc)
        end
        -coef * t
    end
end

function _strong_tuple(values)
    T = promote_type(map(typeof, values)...)
    return ntuple(i -> T(values[i]), length(values))
end

function _strong_tuple(values, n::Int, ::Type{T}) where {T}
    length(values) == n || throw(ArgumentError("expected $n values, got $(length(values))"))
    return ntuple(i -> T(values[i]), n)
end

@element_spec begin
    kind = :thin_strong_beam
    spec_type = ElementSpec{:thin_strong_beam}
    friendly_constructor = ThinStrongBeamSpec
    runtime_type = ThinStrongBeam
    description = "Flexible thin weak-strong beam-beam interaction specification."
    keywords = [:beam_beam, :nonlinear_interaction]
    tracking_methods = [WeakStrongBeamBeamMap]
    contracts = [ElementTrackingBackendConsistencyContract]
    analyses = [PlaceholderAnalysis]
    parameters = (
        kbb=ParamMeta(required=true, meaning="beam-beam kick coefficient"),
        klum=ParamMeta(default=1, meaning="luminosity scale"),
        beta=ParamMeta(meaning="strong-beam beta functions for the uncoupled convenience constructor"),
        alpha=ParamMeta(default=(0, 0), meaning="strong-beam alpha functions"),
        sigma=ParamMeta(meaning="strong-beam transverse sizes for the uncoupled convenience constructor"),
        covariance=ParamMeta(meaning="4 x 4 covariance in (x, px, y, py) order"),
        coupling=ParamMeta(meaning="optional XYCouplingSpec, XYCoupling, or symplectic 4 x 4 matrix"),
        center=ParamMeta(default=(0, 0, 0), meaning="strong-beam closed orbit center"),
        angle=ParamMeta(default=(0, 0, 0), meaning="strong-beam closed orbit angle"),
        curvature=ParamMeta(default=(0, 0, 0), meaning="strong-beam closed orbit curvature"),
        virtual_drift=ParamMeta(default=:hirata, meaning="virtual-drift Hamiltonian: :hirata (default, paraxial, the canonical published synchro-beam map; no path lengthening), :chromatic, or :exact. A model choice, not a numerical knob: it sets an accuracy floor no slice count removes (measured 2.9e-4 / 3.9e-5 in Furman Q at EIC parameters). See docs/theory/gaussian_longitudinal_slicing.md Section 7.1"),
        tracking_method=ParamMeta(default=WeakStrongBeamBeamMap(), meaning="per-element tracking method"),
    )
    example = ThinStrongBeamSpec{Float64}(kbb=1e-4, beta=(1.0, 1.0), sigma=(1e-3, 1e-3))
    construction_help = "Friendly constructor: ThinStrongBeamSpec{T}(; kbb, klum=1, beta=nothing, alpha=(0,0), sigma=nothing, covariance=nothing, coupling=nothing, center=(0,0,0), angle=(0,0,0), curvature=(0,0,0), virtual_drift=:hirata, tracking_method=WeakStrongBeamBeamMap(), kwargs...). Supply beta/sigma or covariance; coupling transforms the uncoupled covariance."
end

@element_spec begin
    kind = :gaussian_strong_beam
    spec_type = ElementSpec{:gaussian_strong_beam}
    friendly_constructor = GaussianStrongBeamSpec
    runtime_type = GaussianStrongBeam
    description = "Flexible sliced Gaussian weak-strong beam-beam interaction specification."
    keywords = [:beam_beam, :nonlinear_interaction]
    tracking_methods = [WeakStrongBeamBeamMap]
    contracts = [ElementTrackingBackendConsistencyContract]
    analyses = [PlaceholderAnalysis]
    parameters = (
        thin=ParamMeta(required=true, meaning="base ThinStrongBeamSpec or ThinStrongBeam"),
        ns=ParamMeta(required=true, meaning="number of longitudinal slices"),
        slice_center=ParamMeta(meaning="explicit slice centers"),
        slice_weight=ParamMeta(meaning="explicit slice weights"),
        slice_hoffset=ParamMeta(meaning="explicit horizontal slice offsets"),
        slice_voffset=ParamMeta(meaning="explicit vertical slice offsets"),
        slice_pxoffset=ParamMeta(meaning="explicit horizontal-angle slice offsets"),
        slice_pyoffset=ParamMeta(meaning="explicit vertical-angle slice offsets"),
        sigz=ParamMeta(meaning="strong-beam longitudinal rms size; required unless explicit slice_center and slice_weight are supplied"),
        mean=ParamMeta(meaning="optional 6D Gaussian mean in (x, px, y, py, z, pz) order"),
        covariance=ParamMeta(meaning="optional 6 x 6 Gaussian covariance; slices use conditional transverse moments"),
        slice_method=ParamMeta(default=:sqrt_density, meaning="longitudinal slicing rule: :sqrt_density (default, Furman #4), :equal_area (#2), :equal_area_centroid (#3), :min_cdf_area (#5), :equal_spacing_density (#1), :gauss_hermite, or :equal_width; see docs/theory/gaussian_longitudinal_slicing.md"),
        slice_width=ParamMeta(meaning="slice width for :equal_width; unused by every other slice_method"),
        hvoffset=ParamMeta(meaning="optional Dict with dim, coef, frequency, harmonics"),
        tracking_method=ParamMeta(default=WeakStrongBeamBeamMap(), meaning="per-element tracking method"),
    )
    example = GaussianStrongBeamSpec{Float64}(thin=ThinStrongBeamSpec{Float64}(kbb=1e-4, beta=(1.0, 1.0), sigma=(1e-3, 1e-3)), ns=3, sigz=0.01)
    construction_help = "Friendly constructor: GaussianStrongBeamSpec{T}(; thin, ns, sigz=nothing, mean=nothing, covariance=nothing, slice_method=:sqrt_density, slice_width=nothing, slice_center=nothing, slice_weight=nothing, slice_hoffset=nothing, slice_voffset=nothing, slice_pxoffset=nothing, slice_pyoffset=nothing, hvoffset=nothing, tracking_method=WeakStrongBeamBeamMap(), kwargs...). A 6 x 6 covariance is conditioned on each longitudinal slice."
end

default_method(::Type{ElementSpec{:thin_strong_beam}}) = WeakStrongBeamBeamMap()
default_method(::Type{ElementSpec{:gaussian_strong_beam}}) = WeakStrongBeamBeamMap()
