export ThinStrongBeamSpec, GaussianStrongBeamSpec,
       ThinStrongBeam, GaussianStrongBeam,
       AbstractVirtualDrift, UnsafeVirtualDrift, HirataParaxialDrift,
       ChromaticDrift, ExactHamiltonianDrift,
       StrongTransverseMoments, transverse_covariance,
       gaussian_strong_beam_covariance, gaussian_beambeam_kick

const ROUND_BEAM_THRESHOLD = 1.0e-10

abstract type ThinStrongBeamSpec{T} end
abstract type GaussianStrongBeamSpec{T} end

"""Strategy used for the canonical IP-to-collision-point virtual drift."""
abstract type AbstractVirtualDrift end

struct _ChromaticFrozenEnergyDrift <: AbstractVirtualDrift end

struct _ParaxialFrozenLongitudinalDrift <: AbstractVirtualDrift end

"""Original paraxial Hirata synchro-beam drift."""
struct HirataParaxialDrift <: AbstractVirtualDrift end

"""Virtual drift generated by `H = (px^2 + py^2) / (2(1 + pz))`."""
struct ChromaticDrift <: AbstractVirtualDrift end

"""Virtual drift generated by the exact field-free Hamiltonian."""
struct ExactHamiltonianDrift <: AbstractVirtualDrift end

const _VIRTUAL_DRIFT_TYPES = (
    hirata=HirataParaxialDrift,
    chromatic=ChromaticDrift,
    exact=ExactHamiltonianDrift,
)

const _UNSAFE_VIRTUAL_DRIFT_TYPES = (
    chromatic_frozen_energy=_ChromaticFrozenEnergyDrift,
    paraxial_frozen_longitudinal=_ParaxialFrozenLongitudinalDrift,
)
const _UnsafeVirtualDriftModel = Union{
    _ChromaticFrozenEnergyDrift,
    _ParaxialFrozenLongitudinalDrift,
}

"""
    UnsafeVirtualDrift(name)

Explicit access to non-symplectic diagnostic approximations. Supported names
are `:paraxial_frozen_longitudinal` and `:chromatic_frozen_energy`. These maps
must not be used for physical six-dimensional tracking.
"""
struct UnsafeVirtualDrift{D<:_UnsafeVirtualDriftModel} <: AbstractVirtualDrift
    model::D
end

function UnsafeVirtualDrift(name::Symbol)
    hasproperty(_UNSAFE_VIRTUAL_DRIFT_TYPES, name) || throw(ArgumentError(
        "unknown unsafe virtual drift :$name; expected one of " *
        "$(keys(_UNSAFE_VIRTUAL_DRIFT_TYPES))"))
    return UnsafeVirtualDrift(getproperty(_UNSAFE_VIRTUAL_DRIFT_TYPES, name)())
end

_virtual_drift(drift::AbstractVirtualDrift) = drift
function _virtual_drift(name::Symbol)
    hasproperty(_VIRTUAL_DRIFT_TYPES, name) || throw(ArgumentError(
        "unknown virtual_drift :$name; expected one of $(keys(_VIRTUAL_DRIFT_TYPES))"))
    return getproperty(_VIRTUAL_DRIFT_TYPES, name)()
end
_virtual_drift(value) = throw(ArgumentError(
    "virtual_drift must be a supported Symbol or AbstractVirtualDrift, got $(typeof(value))"))

"""
    StrongTransverseMoments

Compact, GPU-isbits representation of the strong slice covariance in local
coordinates `(x, px, y, py)`. The covariance is stored as the three blocks
`A = cov((x,y),(x,y))`, `B = cov((x,y),(px,py))`, and
`Q = cov((px,py),(px,py))`. The Boolean type parameter records whether
cross-plane coupling is present, allowing the uncoupled hot path to remain
compile-time specialized.
"""
struct StrongTransverseMoments{T,Coupled}
    a0::T
    b0::T
    d0::T
    bxx::T
    bxpy::T
    bypx::T
    bypy::T
    qxx::T
    qxy::T
    qyy::T
end

function transverse_covariance(m::StrongTransverseMoments{T}) where {T}
    covariance = zeros(T, 4, 4)
    covariance[1, 1] = m.a0
    covariance[1, 2] = covariance[2, 1] = m.bxx
    covariance[1, 3] = covariance[3, 1] = m.b0
    covariance[1, 4] = covariance[4, 1] = m.bxpy
    covariance[2, 2] = m.qxx
    covariance[2, 3] = covariance[3, 2] = m.bypx
    covariance[2, 4] = covariance[4, 2] = m.qxy
    covariance[3, 3] = m.d0
    covariance[3, 4] = covariance[4, 3] = m.bypy
    covariance[4, 4] = m.qyy
    return covariance
end

"""
    ThinStrongBeamSpec{T=Float64}(; kbb, klum=1, beta=nothing,
                                  alpha=(0,0), sigma=nothing,
                                  covariance=nothing, coupling=nothing,
                                  center=(0,0,0), angle=(0,0,0),
                                  curvature=(0,0,0), virtual_drift=:hirata,
                                  tracking_method=WeakStrongBeamBeamMap(),
                                  kwargs...)

Create an `ElementSpec{:thin_strong_beam}` for a weak-strong beam-beam
interaction. Supply either the legacy uncoupled `(beta, alpha, sigma)` data or
a symmetric `4 x 4` covariance in `(x, px, y, py)` order. `coupling` may be an
`XYCouplingSpec`, an `XYCoupling`, or a `4 x 4` linear matrix; it transforms
the uncoupled covariance before compilation.

Turn-dependent modulation is deliberately not part of this element. It belongs
in a scheduled task action, keeping the runtime element a compact description
of collision physics.
"""
ThinStrongBeamSpec(; kwargs...) = ThinStrongBeamSpec{Float64}(; kwargs...)
function (::Type{ThinStrongBeamSpec{T}})(; kbb,
                                        klum=one(T),
                                        beta=nothing,
                                        alpha=(zero(T), zero(T)),
                                        sigma=nothing,
                                        covariance=nothing,
                                        coupling=nothing,
                                        center=(zero(T), zero(T), zero(T)),
                                        angle=(zero(T), zero(T), zero(T)),
                                        curvature=(zero(T), zero(T), zero(T)),
                                        virtual_drift=:hirata,
                                        tracking_method=WeakStrongBeamBeamMap(),
                                        kwargs...) where {T}
    covariance4 = transverse_covariance(T;
        beta=beta, alpha=alpha, sigma=sigma,
        covariance=covariance, coupling=coupling)
    return ElementSpec{:thin_strong_beam}(
        _spec_params(;
            kbb=T(kbb),
            klum=T(klum),
            covariance=covariance4,
            center=_strong_tuple(center, 3, T),
            angle=_strong_tuple(angle, 3, T),
            curvature=_strong_tuple(curvature, 3, T),
            virtual_drift=_virtual_drift(virtual_drift),
            tracking_method=tracking_method,
            kwargs...,
        ),
    )
end

mutable struct ThinStrongBeam{M<:AbstractTrackingMethod,T<:AbstractFloat,
                              P<:StrongTransverseMoments,D<:AbstractVirtualDrift} <: AbstractTrackOp
    method::M
    moments::P
    kbb::T
    klum::T
    xo::T
    yo::T
    zo::T
    pxo::T
    pyo::T
    pzo::T
    ppxo::T
    ppyo::T
    ppzo::T
    virtual_drift::D
    last_luminosity::T
end

function ThinStrongBeam(spec::ElementSpec{:thin_strong_beam},
                        method::AbstractTrackingMethod=tracking_method(spec))
    covariance4 = param(spec, :covariance)
    center = param(spec, :center)
    angle = param(spec, :angle)
    curvature = param(spec, :curvature)
    T = promote_type(map(typeof, (covariance4..., center..., angle..., curvature...,
                                  param(spec, :kbb), param(spec, :klum)))...)
    moments = _strong_transverse_moments(covariance4, T)
    return ThinStrongBeam(
        method,
        moments,
        T(param(spec, :kbb)),
        T(param(spec, :klum)),
        T(center[1]), T(center[2]), T(center[3]),
        T(angle[1]), T(angle[2]), T(angle[3]),
        T(curvature[1]), T(curvature[2]), T(curvature[3]),
        param(spec, :virtual_drift),
        zero(T),
    )
end

"""
    GaussianStrongBeamSpec{T=Float64}(; thin, ns, slice_center=nothing,
                                      slice_weight=nothing,
                                      slice_hoffset=nothing,
                                      slice_voffset=nothing,
                                      slice_pxoffset=nothing,
                                      slice_pyoffset=nothing,
                                      sigz=nothing,
                                      mean=nothing,
                                      covariance=nothing,
                                      slice_method=:equal_area,
                                      slice_width=nothing,
                                      hvoffset=nothing,
                                      tracking_method=WeakStrongBeamBeamMap(),
                                      kwargs...)

Create an `ElementSpec{:gaussian_strong_beam}`. `thin` may be a
`ThinStrongBeamSpec` or a compiled `ThinStrongBeam`.

When `covariance` is supplied it is the full `6 x 6` covariance in
`(x, px, y, py, z, pz)` order. Each thin longitudinal slice is constructed
from the conditional transverse Gaussian at its slice coordinate. Therefore
linear crab dispersion changes slice centroids, while momentum dispersion is
retained in the conditional within-slice covariance. `mean` defaults to the
centroid and angle stored in `thin`.
"""
GaussianStrongBeamSpec(; kwargs...) = GaussianStrongBeamSpec{Float64}(; kwargs...)
function (::Type{GaussianStrongBeamSpec{T}})(; thin,
                                            ns,
                                            slice_center=nothing,
                                            slice_weight=nothing,
                                            slice_hoffset=nothing,
                                            slice_voffset=nothing,
                                            slice_pxoffset=nothing,
                                            slice_pyoffset=nothing,
                                            sigz=nothing,
                                            mean=nothing,
                                            covariance=nothing,
                                            slice_method=:equal_area,
                                            slice_width=nothing,
                                            hvoffset=nothing,
                                            tracking_method=WeakStrongBeamBeamMap(),
                                            kwargs...) where {T}
    return ElementSpec{:gaussian_strong_beam}(
        _spec_params(;
            thin=thin,
            ns=Int(ns),
            sigz=sigz === nothing ? nothing : T(sigz),
            slice_method=slice_method,
            slice_width=slice_width,
            slice_center=slice_center === nothing ? nothing : _strong_tuple(slice_center, Int(ns), T),
            slice_weight=slice_weight === nothing ? nothing : _strong_tuple(slice_weight, Int(ns), T),
            slice_hoffset=slice_hoffset === nothing ? nothing : _strong_tuple(slice_hoffset, Int(ns), T),
            slice_voffset=slice_voffset === nothing ? nothing : _strong_tuple(slice_voffset, Int(ns), T),
            slice_pxoffset=slice_pxoffset === nothing ? nothing : _strong_tuple(slice_pxoffset, Int(ns), T),
            slice_pyoffset=slice_pyoffset === nothing ? nothing : _strong_tuple(slice_pyoffset, Int(ns), T),
            mean=mean === nothing ? nothing : _strong_tuple(mean, 6, T),
            covariance=covariance === nothing ? nothing : _validated_covariance(covariance, 6, T),
            hvoffset=hvoffset,
            tracking_method=tracking_method,
            kwargs...,
        ),
    )
end

mutable struct GaussianStrongBeam{M<:AbstractTrackingMethod,T<:AbstractFloat,
                                  P<:StrongTransverseMoments,
                                  D<:AbstractVirtualDrift,SliceAngles} <: AbstractTrackOp
    method::M
    ns::Int
    slice_center::Vector{T}
    slice_weight::Vector{T}
    slice_hoffset::Vector{T}
    slice_voffset::Vector{T}
    slice_pxoffset::Vector{T}
    slice_pyoffset::Vector{T}
    thin::ThinStrongBeam{M,T,P,D}
    last_luminosity::T
end

function GaussianStrongBeam(spec::ElementSpec{:gaussian_strong_beam},
                            method::AbstractTrackingMethod=tracking_method(spec))
    thin_raw = param(spec, :thin)
    thin = thin_raw isa ThinStrongBeam ? thin_raw : ThinStrongBeam(thin_raw, method)
    T0 = typeof(thin.kbb)
    covariance6 = getparam(spec, :covariance, nothing)
    crab_slope = ntuple(_ -> zero(T0), 4)
    if covariance6 !== nothing
        mean6 = getparam(spec, :mean, nothing)
        mean6 = mean6 === nothing ?
            (thin.xo, thin.pxo, thin.yo, thin.pyo, thin.zo, thin.pzo) :
            _strong_tuple(mean6, 6, T0)
        conditional4, crab_slope = _conditional_transverse_gaussian(covariance6, T0)
        thin = _thin_with_distribution(thin, conditional4, mean6)
    end
    sigz = getparam(spec, :sigz, nothing)
    if sigz === nothing && covariance6 !== nothing
        sigz = sqrt(T0(covariance6[5, 5]))
    end
    centers_tuple, weights_tuple = _gaussian_slices(
        T0,
        Int(param(spec, :ns)),
        getparam(spec, :slice_center, nothing),
        getparam(spec, :slice_weight, nothing),
        sigz,
        getparam(spec, :slice_method, :equal_area),
        getparam(spec, :slice_width, nothing),
    )
    hoff_tuple = getparam(spec, :slice_hoffset, nothing)
    voff_tuple = getparam(spec, :slice_voffset, nothing)
    pxoff_tuple = getparam(spec, :slice_pxoffset, nothing)
    pyoff_tuple = getparam(spec, :slice_pyoffset, nothing)
    hoff_tuple = hoff_tuple === nothing ? ntuple(_ -> zero(T0), Int(param(spec, :ns))) : _strong_tuple(hoff_tuple, Int(param(spec, :ns)), T0)
    voff_tuple = voff_tuple === nothing ? ntuple(_ -> zero(T0), Int(param(spec, :ns))) : _strong_tuple(voff_tuple, Int(param(spec, :ns)), T0)
    pxoff_tuple = pxoff_tuple === nothing ? ntuple(_ -> zero(T0), Int(param(spec, :ns))) : _strong_tuple(pxoff_tuple, Int(param(spec, :ns)), T0)
    pyoff_tuple = pyoff_tuple === nothing ? ntuple(_ -> zero(T0), Int(param(spec, :ns))) : _strong_tuple(pyoff_tuple, Int(param(spec, :ns)), T0)
    if covariance6 !== nothing
        hoff_tuple = ntuple(i -> hoff_tuple[i] + crab_slope[1] * centers_tuple[i], length(centers_tuple))
        pxoff_tuple = ntuple(i -> pxoff_tuple[i] + crab_slope[2] * centers_tuple[i], length(centers_tuple))
        voff_tuple = ntuple(i -> voff_tuple[i] + crab_slope[3] * centers_tuple[i], length(centers_tuple))
        pyoff_tuple = ntuple(i -> pyoff_tuple[i] + crab_slope[4] * centers_tuple[i], length(centers_tuple))
    end
    hvoffset = getparam(spec, :hvoffset, nothing)
    if hvoffset !== nothing
        dim = Symbol(get(hvoffset, :dim, :x))
        offsets = _crab_offsets(centers_tuple, T0(get(hvoffset, :coef, 0.0)),
                                T0(get(hvoffset, :frequency, -1.0)),
                                get(hvoffset, :harmonics, Dict(1 => 1.0)))
        if dim == :x
            hoff_tuple = ntuple(i -> hoff_tuple[i] + offsets[i], length(offsets))
        elseif dim == :y
            voff_tuple = ntuple(i -> voff_tuple[i] + offsets[i], length(offsets))
        else
            throw(ArgumentError("hvoffset dim must be :x or :y"))
        end
    end
    centers = collect(centers_tuple)
    weights = collect(weights_tuple)
    hoff = collect(hoff_tuple)
    voff = collect(voff_tuple)
    pxoff = collect(pxoff_tuple)
    pyoff = collect(pyoff_tuple)
    T = promote_type(map(typeof, (centers..., weights..., hoff..., voff..., pxoff..., pyoff...))...)
    slice_angles = any(!iszero, pxoff) || any(!iszero, pyoff)
    return GaussianStrongBeam{typeof(method),T,typeof(thin.moments),
                              typeof(thin.virtual_drift),slice_angles}(
        method, Int(param(spec, :ns)),
        T.(centers), T.(weights), T.(hoff), T.(voff),
        T.(pxoff), T.(pyoff), thin, zero(T))
end

@inline function track_particle(::WeakStrongBeamBeamMap, elem::ThinStrongBeam,
                                x, px, y, py, z, pz)
    x1, px1, y1, py1, z1, pz1, _ = _thin_strong_beam_track(elem, x, px, y, py, z, pz)
    return x1, px1, y1, py1, z1, pz1
end

@inline function track_particle(::WeakStrongBeamBeamMap, elem::GaussianStrongBeam,
                                x, px, y, py, z, pz)
    lum = zero(x + px + y + py + z + pz)
    kbb0 = elem.thin.kbb
    x0, y0, z0 = elem.thin.xo, elem.thin.yo, elem.thin.zo
    for i in elem.ns:-1:1
        slice_pxo, slice_pyo = _slice_transverse_angles(elem, i)
        thin = _slice_thin_strong_beam(elem.thin,
                                       kbb0 * elem.slice_weight[i],
                                       x0 + elem.slice_hoffset[i],
                                       y0 + elem.slice_voffset[i],
                                       z0 + elem.slice_center[i],
                                       slice_pxo, slice_pyo)
        x, px, y, py, z, pz, l = _thin_strong_beam_track(thin, x, px, y, py, z, pz)
        lum += l * elem.slice_weight[i]
    end
    return x, px, y, py, z, pz
end

@inline (elem::ThinStrongBeam)(x, px, y, py, z, pz) =
    track_particle(elem.method, elem, x, px, y, py, z, pz)
@inline (elem::GaussianStrongBeam)(x, px, y, py, z, pz) =
    track_particle(elem.method, elem, x, px, y, py, z, pz)

function _thin_strong_beam_track(elem::ThinStrongBeam, x, px, y, py, z, pz)
    (elem.moments.a0 == 0 || elem.moments.d0 == 0) && return x, px, y, py, z, pz, zero(x)
    x, px, y, py, z, pz, S = _dynamic_drift(elem, x, px, y, py, z, pz)
    x, px, y, py, z, pz, lum = _cp_kick(elem, S, x, px, y, py, z, pz)
    x, px, y, py, z, pz = _reverse_dynamic_drift(elem, x, px, y, py, z, pz)
    return x, px, y, py, z, pz, lum * elem.klum
end

function _slice_thin_strong_beam(base::ThinStrongBeam{M,T}, kbb, xo, yo, zo,
                                 pxo=base.pxo, pyo=base.pyo) where {M,T}
    return ThinStrongBeam(
        base.method,
        base.moments,
        T(kbb), base.klum,
        T(xo), T(yo), T(zo),
        T(pxo), T(pyo), base.pzo,
        base.ppxo, base.ppyo, base.ppzo,
        base.virtual_drift,
        zero(T),
    )
end

@inline _dynamic_drift(elem::ThinStrongBeam, x, px, y, py, z, pz) =
    _forward_virtual_drift(elem.virtual_drift, x, px, y, py, z, pz, elem.zo)

@inline _reverse_dynamic_drift(elem::ThinStrongBeam, x, px, y, py, z, pz) =
    _reverse_virtual_drift(elem.virtual_drift, x, px, y, py, z, pz, elem.zo)

@inline function _forward_virtual_drift(
        ::_ChromaticFrozenEnergyDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    phi = sqrt(1 - 0.5 * (px * px + py * py) / ((1 + pz) * (1 + pz))) - 1
    x += S * px / (1 + pz)
    y += S * py / (1 + pz)
    z += 2 * S * phi
    return x, px, y, py, z, pz, S
end

@inline function _reverse_virtual_drift(
        ::_ChromaticFrozenEnergyDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    psi = sqrt(1 + 0.5 * (px * px + py * py) / ((1 + pz) * (1 + pz))) - 1
    x -= S * px / (1 + pz)
    y -= S * py / (1 + pz)
    z += 2 * S * psi
    return x, px, y, py, z, pz
end

@inline function _forward_virtual_drift(
        ::_ParaxialFrozenLongitudinalDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    x += S * px
    y += S * py
    return x, px, y, py, z, pz, S
end

@inline function _reverse_virtual_drift(
        ::_ParaxialFrozenLongitudinalDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    x -= S * px
    y -= S * py
    return x, px, y, py, z, pz
end

@inline _forward_virtual_drift(
        drift::UnsafeVirtualDrift, x, px, y, py, z, pz, zo) =
    _forward_virtual_drift(drift.model, x, px, y, py, z, pz, zo)

@inline _reverse_virtual_drift(
        drift::UnsafeVirtualDrift, x, px, y, py, z, pz, zo) =
    _reverse_virtual_drift(drift.model, x, px, y, py, z, pz, zo)

@inline function _forward_virtual_drift(
        ::HirataParaxialDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    x += S * px
    y += S * py
    pz -= 0.25 * (px * px + py * py)
    return x, px, y, py, z, pz, S
end

@inline function _reverse_virtual_drift(
        ::HirataParaxialDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    x -= S * px
    y -= S * py
    pz += 0.25 * (px * px + py * py)
    return x, px, y, py, z, pz
end

@inline function _forward_virtual_drift(
        ::ChromaticDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    phi = sqrt(1 - 0.5 * (px * px + py * py) / ((1 + pz) * (1 + pz))) - 1
    x += S * px / (1 + pz)
    y += S * py / (1 + pz)
    z += 2 * S * phi
    pz += (1 + pz) * phi
    return x, px, y, py, z, pz, S
end

@inline function _reverse_virtual_drift(
        ::ChromaticDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    psi = sqrt(1 + 0.5 * (px * px + py * py) / ((1 + pz) * (1 + pz))) - 1
    x -= S * px / (1 + pz)
    y -= S * py / (1 + pz)
    z += 2 * S * psi
    pz += (1 + pz) * psi
    return x, px, y, py, z, pz
end

@inline function _forward_virtual_drift(
        ::ExactHamiltonianDrift, x, px, y, py, z, pz, zo)
    ps = sqrt((1 + pz) * (1 + pz) - px * px - py * py)
    H = 1 + pz - ps
    rr = 0.5 * H / ps
    z2 = (z + rr * zo) / (1 + rr)
    S = 0.5 * (z2 - zo)
    z -= H / ps * S
    pz -= 0.5 * H
    x += px / ps * S
    y += py / ps * S
    return x, px, y, py, z, pz, S
end

@inline function _reverse_virtual_drift(
        ::ExactHamiltonianDrift, x, px, y, py, z, pz, zo)
    S = 0.5 * (z - zo)
    H0 = 0.5 * (px * px + py * py) / (1 + pz)
    ps0 = 1 + pz - 0.5 * H0
    pz += 0.5 * H0
    x -= px / ps0 * S
    y -= py / ps0 * S
    z += H0 / ps0 * S
    return x, px, y, py, z, pz
end

@inline function _cp_kick(elem::ThinStrongBeam, S, x, px, y, py, z, pz)
    xx = x - elem.xo + elem.pxo * S - 0.5 * elem.ppxo * S * S
    yy = y - elem.yo + elem.pyo * S - 0.5 * elem.ppyo * S * S
    px0, py0 = px, py
    x, px, y, py, z, pz, density = _cp_covariance_kick(
        elem.moments, elem.kbb, S, xx, yy, x, px, y, py, z, pz)
    centroid_u_x = elem.pxo - elem.ppxo * S
    centroid_u_y = elem.pyo - elem.ppyo * S
    pz += 0.5 * ((px - px0) * centroid_u_x + (py - py0) * centroid_u_y)
    return x, px, y, py, z, pz, density
end

@inline function _cp_covariance_kick(m::StrongTransverseMoments{T,false}, kbb,
                                     S, xx, yy, x, px, y, py, z, pz) where {T}
    a, _, d, au, _, du = _transport_transverse_moments(m, S)
    (a <= 0 || d <= 0) && return x, px, y, py, z, pz, zero(x)
    sigx, sigy = sqrt(a), sqrt(d)
    Kx, Ky = gaussian_beambeam_kick(sigx, sigy, xx, yy)
    expterm = exp(-0.5 * (xx * xx / (sigx * sigx) + yy * yy / (sigy * sigy)))
    Fx, Fy = Kx * kbb, Ky * kbb
    px += Fx
    py += Fy
    dsize = abs(sigx - sigy) / 2
    msize = (sigx + sigy) / 2
    if dsize / msize < ROUND_BEAM_THRESHOLD
        Hxx, _, Hyy = _round_gaussian_hessian(kbb, msize, xx, yy, expterm)
    else
        Hxx, Hyy = _elliptic_gaussian_hessian_diagonal(
            kbb, sigx, sigy, xx, yy, Kx, Ky, expterm)
    end
    pz += 0.25 * (Hxx * au + Hyy * du)
    return x, px, y, py, z, pz, expterm / TWOPI / sigx / sigy
end

@inline function _cp_covariance_kick(m::StrongTransverseMoments{T,true}, kbb,
                                     S, xx, yy, x, px, y, py, z, pz) where {T}
    a, b, d, au, bu, du = _transport_transverse_moments(m, S)
    detA = a * d - b * b
    (a <= 0 || d <= 0 || detA <= 0) && return x, px, y, py, z, pz, zero(x)
    D = sqrt((a - d) * (a - d) + 4 * b * b)
    if D <= ROUND_BEAM_THRESHOLD * (a + d)
        sigma = sqrt((a + d) / 2)
        Kx, Ky = gaussian_beambeam_kick(sigma, sigma, xx, yy)
        expterm = exp(-0.5 * (xx * xx + yy * yy) / (sigma * sigma))
        Fx, Fy = kbb * Kx, kbb * Ky
        Hxx, Hxy, Hyy = _round_gaussian_hessian(kbb, sigma, xx, yy, expterm)
        px += Fx
        py += Fy
        pz += 0.25 * (Hxx * au + 2 * Hxy * bu + Hyy * du)
        return x, px, y, py, z, pz, expterm / (TWOPI * sigma * sigma)
    end

    theta = 0.5 * atan(2 * b, a - d)
    c, s = cos(theta), sin(theta)
    lambda1 = (a + d + D) / 2
    lambda2 = (a + d - D) / 2
    sig1, sig2 = sqrt(lambda1), sqrt(lambda2)
    xh = c * xx + s * yy
    yh = -s * xx + c * yy
    Kxh, Kyh = gaussian_beambeam_kick(sig1, sig2, xh, yh)
    expterm = exp(-0.5 * (xh * xh / lambda1 + yh * yh / lambda2))
    Fxh, Fyh = kbb * Kxh, kbb * Kyh
    Fx = c * Fxh - s * Fyh
    Fy = s * Fxh + c * Fyh
    px += Fx
    py += Fy

    H11, H22 = _elliptic_gaussian_hessian_diagonal(
        kbb, sig1, sig2, xh, yh, Kxh, Kyh, expterm)
    Du = ((a - d) * (au - du) + 4 * b * bu) / D
    lambda1u = (au + du + Du) / 2
    lambda2u = (au + du - Du) / 2
    thetau = ((a - d) * bu - b * (au - du)) / (D * D)
    pz += 0.25 * (H11 * lambda1u + H22 * lambda2u)
    pz -= 0.5 * thetau * (Fxh * yh - Fyh * xh)
    return x, px, y, py, z, pz, expterm / (TWOPI * sig1 * sig2)
end

@inline function _transport_transverse_moments(m::StrongTransverseMoments, S)
    a = m.a0 - 2 * S * m.bxx + S * S * m.qxx
    b = m.b0 - S * (m.bxpy + m.bypx) + S * S * m.qxy
    d = m.d0 - 2 * S * m.bypy + S * S * m.qyy
    au = 2 * (m.bxx - S * m.qxx)
    bu = m.bxpy + m.bypx - 2 * S * m.qxy
    du = 2 * (m.bypy - S * m.qyy)
    return a, b, d, au, bu, du
end

@inline function _elliptic_gaussian_hessian_diagonal(kbb, sigx, sigy,
                                                       x, y, Kx, Ky, expterm)
    temp1 = kbb * (x * Kx + y * Ky)
    temp2 = sigx * sigx - sigy * sigy
    temp3 = sigy / sigx
    Hxx = (temp1 - 2 * kbb * (1 - expterm * temp3)) / temp2
    Hyy = (-temp1 + 2 * kbb * (1 - expterm / temp3)) / temp2
    return Hxx, Hyy
end

@inline function _round_gaussian_hessian(kbb, sigma, x, y, expterm)
    r2 = x * x + y * y
    sigma2 = sigma * sigma
    if r2 == 0
        h = -kbb / sigma2
        return h, zero(h), h
    end
    f = 2 * (1 - expterm) / r2
    fp = 2 * (expterm * r2 / (2 * sigma2) - (1 - expterm)) / (r2 * r2)
    Hxx = -kbb * (f + 2 * x * x * fp)
    Hxy = -kbb * (2 * x * y * fp)
    Hyy = -kbb * (f + 2 * y * y * fp)
    return Hxx, Hxy, Hyy
end

function gaussian_beambeam_kick(sigx, sigy, x, y)
    (sigx == 0 || sigy == 0) && return zero(x), zero(y)
    dsize = abs((sigx - sigy) / 2)
    msize = sigx - (sigx - sigy) / 2
    negx = x < 0
    negy = y < 0
    x = abs(x)
    y = abs(y)
    if dsize / msize < ROUND_BEAM_THRESHOLD
        rr = x * x + y * y
        if rr == 0
            return zero(x), zero(y)
        end
        temp = 2 * (1 - exp(-rr / (2 * msize * msize))) / rr
        Kx = temp * x
        Ky = temp * y
    else
        if sigx > sigy
            sig1, sig2, x1, x2 = sigx, sigy, x, y
        else
            sig1, sig2, x1, x2 = sigy, sigx, y, x
        end
        denominator = SQRT2 * sqrt(sig1 * sig1 - sig2 * sig2)
        z1 = complex(x1 / denominator, x2 / denominator)
        z2 = complex(sig2 / sig1 * x1 / denominator, sig1 / sig2 * x2 / denominator)
        A = 2 * SQRTPI / denominator
        B = exp(-x1 * x1 / (2 * sig1 * sig1) - x2 * x2 / (2 * sig2 * sig2))
        ret = A * (faddeeva_w(z1) - B * faddeeva_w(z2))
        if sigx > sigy
            Ky = real(ret)
            Kx = imag(ret)
        else
            Ky = imag(ret)
            Kx = real(ret)
        end
    end
    return negx ? -Kx : Kx, negy ? -Ky : Ky
end

"""
    transverse_covariance([T=Float64]; beta, alpha=(0,0), sigma,
                           covariance=nothing, coupling=nothing)

Return the strong-slice `4 x 4` covariance in `(x, px, y, py)` order.
Either provide `covariance` directly, or provide uncoupled Twiss data. An
optional `coupling` linear map is applied as `M * covariance * M'`.
"""
transverse_covariance(; kwargs...) = transverse_covariance(Float64; kwargs...)
function transverse_covariance(::Type{T}; beta=nothing,
                               alpha=(zero(T), zero(T)), sigma=nothing,
                               covariance=nothing, coupling=nothing) where {T}
    if covariance === nothing
        beta === nothing && throw(ArgumentError(
            "ThinStrongBeamSpec requires beta and sigma, or a 4 x 4 covariance"))
        sigma === nothing && throw(ArgumentError(
            "ThinStrongBeamSpec requires beta and sigma, or a 4 x 4 covariance"))
        beta2 = _strong_tuple(beta, 2, T)
        alpha2 = _strong_tuple(alpha, 2, T)
        sigma2 = _strong_tuple(sigma, 2, T)
        all(>(zero(T)), beta2) || throw(ArgumentError("strong-beam beta functions must be positive"))
        all(>(zero(T)), sigma2) || throw(ArgumentError("strong-beam transverse sizes must be positive"))
        cov4 = zeros(T, 4, 4)
        for (i, q, p) in ((1, 1, 2), (2, 3, 4))
            emit = sigma2[i] * sigma2[i] / beta2[i]
            gamma = (one(T) + alpha2[i] * alpha2[i]) / beta2[i]
            cov4[q, q] = sigma2[i] * sigma2[i]
            cov4[q, p] = cov4[p, q] = -emit * alpha2[i]
            cov4[p, p] = emit * gamma
        end
    else
        beta === nothing || throw(ArgumentError("beta/sigma and covariance are alternative strong-beam descriptions"))
        sigma === nothing || throw(ArgumentError("beta/sigma and covariance are alternative strong-beam descriptions"))
        coupling === nothing || throw(ArgumentError("apply coupling before supplying an explicit covariance"))
        return _validated_covariance(covariance, 4, T)
    end
    if coupling !== nothing
        matrix = _xy_coupling_matrix(coupling, T)
        cov4 = matrix * cov4 * transpose(matrix)
    end
    return _validated_covariance(cov4, 4, T)
end

"""
    gaussian_strong_beam_covariance(transverse, longitudinal;
                                    crab_dispersion=(0,0,0,0),
                                    momentum_dispersion=(0,0,0,0))

Construct a `6 x 6` Gaussian covariance in `(x, px, y, py, z, pz)` order from
an intrinsic transverse covariance, a `2 x 2` longitudinal covariance, and
linear relations `w = w_beta + crab_dispersion*z + momentum_dispersion*pz`.
"""
function gaussian_strong_beam_covariance(transverse, longitudinal;
        crab_dispersion=(0, 0, 0, 0), momentum_dispersion=(0, 0, 0, 0))
    T = promote_type(eltype(transverse), eltype(longitudinal),
                     map(typeof, (crab_dispersion..., momentum_dispersion...))...)
    transverse4 = _validated_covariance(transverse, 4, T)
    longitudinal2 = _validated_covariance(longitudinal, 2, T)
    zeta = collect(_strong_tuple(crab_dispersion, 4, T))
    eta = collect(_strong_tuple(momentum_dispersion, 4, T))
    dispersion = hcat(zeta, eta)
    cov6 = zeros(T, 6, 6)
    cov6[1:4, 1:4] .= transverse4 .+ dispersion * longitudinal2 * transpose(dispersion)
    cov6[1:4, 5:6] .= dispersion * longitudinal2
    cov6[5:6, 1:4] .= transpose(cov6[1:4, 5:6])
    cov6[5:6, 5:6] .= longitudinal2
    return _validated_covariance(cov6, 6, T)
end

function _validated_covariance(covariance, n::Int, ::Type{T}) where {T}
    size(covariance) == (n, n) || throw(ArgumentError("expected a $n x $n covariance"))
    cov = Matrix{T}(covariance)
    all(isfinite, cov) || throw(ArgumentError("covariance entries must be finite"))
    scale = maximum(abs, cov)
    symmetry_tolerance = T(100) * eps(T) * max(scale, one(T))
    maximum(abs, cov - transpose(cov)) <= symmetry_tolerance ||
        throw(ArgumentError("covariance must be symmetric"))
    cov = (cov + transpose(cov)) / 2
    psd_tolerance = T(100) * eps(T) * max(scale, eps(T))
    minimum(eigvals(Symmetric(cov))) >= -psd_tolerance ||
        throw(ArgumentError("covariance must be positive semidefinite"))
    return cov
end

function _xy_coupling_matrix(coupling, ::Type{T}) where {T}
    if coupling isa AbstractMatrix
        matrix = Matrix{T}(coupling)
    else
        runtime = coupling isa ElementSpec{:xy_coupling} ? XYCoupling(coupling) : coupling
        runtime isa XYCoupling || throw(ArgumentError(
            "coupling must be an XYCouplingSpec, XYCoupling, or 4 x 4 matrix"))
        matrix = zeros(T, 4, 4)
        for column in 1:4
            input = ntuple(i -> i == column ? one(T) : zero(T), 4)
            output = track_particle(runtime.method, runtime, input[1], input[2],
                                    input[3], input[4], zero(T), zero(T))
            matrix[:, column] .= output[1:4]
        end
    end
    size(matrix) == (4, 4) || throw(ArgumentError("coupling matrix must be 4 x 4"))
    all(isfinite, matrix) || throw(ArgumentError("coupling matrix entries must be finite"))
    J = T[0 1 0 0; -1 0 0 0; 0 0 0 1; 0 0 -1 0]
    residual = transpose(matrix) * J * matrix - J
    tolerance = T(500) * eps(T) * max(opnorm(matrix)^2, one(T))
    opnorm(residual, Inf) <= tolerance || throw(ArgumentError("coupling matrix must be symplectic"))
    return matrix
end

function _strong_transverse_moments(covariance4, ::Type{T}) where {T}
    cov = _validated_covariance(covariance4, 4, T)
    coupled = !(iszero(cov[1, 3]) && iszero(cov[1, 4]) &&
                iszero(cov[2, 3]) && iszero(cov[2, 4]))
    return StrongTransverseMoments{T,coupled}(
        cov[1, 1], cov[1, 3], cov[3, 3],
        cov[1, 2], cov[1, 4], cov[3, 2], cov[3, 4],
        cov[2, 2], cov[2, 4], cov[4, 4])
end

function _conditional_transverse_gaussian(covariance6, ::Type{T}) where {T}
    cov = _validated_covariance(covariance6, 6, T)
    variance_z = cov[5, 5]
    variance_z > zero(T) || throw(ArgumentError(
        "a sliced 6D Gaussian requires positive longitudinal position variance"))
    wz = cov[1:4, 5]
    slope = Tuple(wz ./ variance_z)
    conditional = cov[1:4, 1:4] - wz * transpose(wz) / variance_z
    return _validated_covariance(conditional, 4, T), slope
end

function _thin_with_distribution(base::ThinStrongBeam{M,T}, covariance4, mean6) where {M,T}
    moments = _strong_transverse_moments(covariance4, T)
    return ThinStrongBeam(
        base.method, moments, base.kbb, base.klum,
        T(mean6[1]), T(mean6[3]), T(mean6[5]),
        T(mean6[2]), T(mean6[4]), T(mean6[6]),
        base.ppxo, base.ppyo, base.ppzo,
        base.virtual_drift, zero(T))
end

function _gaussian_slices(::Type{T}, ns::Int, slice_center, slice_weight, sigz, method, width) where {T}
    if slice_center !== nothing && slice_weight !== nothing
        return _strong_tuple(slice_center, ns, T), _strong_tuple(slice_weight, ns, T)
    end
    sigz === nothing && throw(ArgumentError("GaussianStrongBeamSpec requires sigz unless slice_center and slice_weight are supplied"))
    method == :equal_area && return _equal_area_slices(T, ns, T(sigz))
    method == :equal_width && return _equal_width_slices(T, ns, T(sigz), T(width))
    throw(ArgumentError("unknown slice_method $method"))
end

function _equal_area_slices(::Type{T}, ns::Int, sigz::T) where {T}
    centers = zeros(T, ns)
    weights = fill(inv(T(ns)), ns)
    rr = SQRT2 * sigz
    if isodd(ns)
        w = (ns - 1) ÷ 2
        centers[w + 1] = zero(T)
        for i in 1:w
            centers[i + w + 1] = inverse_erf(2 * i / ns) * rr
            centers[-i + w + 1] = -centers[i + w + 1]
        end
    else
        w = ns ÷ 2
        for i in 1:w
            centers[i + w] = inverse_erf((2 * i - 1) / ns) * rr
            centers[-i + w + 1] = -centers[i + w]
        end
    end
    return Tuple(centers), Tuple(weights)
end

function _equal_width_slices(::Type{T}, ns::Int, sigz::T, width::T) where {T}
    centers = zeros(T, ns)
    weights = zeros(T, ns)
    nw = width / SQRT2 / sigz
    sumw = erf(nw * ns / 2)
    if isodd(ns)
        w = (ns - 1) ÷ 2
        upper = erf(0.5 * nw)
        weights[w + 1] = upper / sumw
        for i in 1:w
            centers[i + w + 1] = width * i
            centers[-i + w + 1] = -centers[i + w + 1]
            lower = upper
            upper = erf((i + 0.5) * nw)
            weights[i + w + 1] = (upper - lower) / 2 / sumw
            weights[-i + w + 1] = weights[i + w + 1]
        end
    else
        w = ns ÷ 2
        upper = zero(T)
        for i in 1:w
            centers[i + w] = (i - 0.5) * width
            centers[-i + w + 1] = -centers[i + w]
            lower = upper
            upper = erf(i * nw)
            weights[i + w] = (upper - lower) / 2 / sumw
            weights[-i + w + 1] = weights[i + w]
        end
    end
    return Tuple(centers), Tuple(weights)
end

function _crab_offsets(centers, coef, freq, harmonics)
    freq <= 0 && return ntuple(_ -> zero(coef), length(centers))
    kcc = TWOPI * freq / CLIGHT
    return ntuple(length(centers)) do i
        t = -centers[i]
        for (h, rel) in pairs(harmonics)
            t += rel * sin(h * kcc * centers[i]) / (h * kcc)
        end
        -coef * t
    end
end

function _strong_tuple(values)
    T = promote_type(map(typeof, values)...)
    return ntuple(i -> T(values[i]), length(values))
end

function _strong_tuple(values, n::Int, ::Type{T}) where {T}
    length(values) == n || throw(ArgumentError("expected $n values, got $(length(values))"))
    return ntuple(i -> T(values[i]), n)
end

@element_spec begin
    kind = :thin_strong_beam
    spec_type = ElementSpec{:thin_strong_beam}
    friendly_constructor = ThinStrongBeamSpec
    runtime_type = ThinStrongBeam
    description = "Flexible thin weak-strong beam-beam interaction specification."
    keywords = [:beam_beam, :nonlinear_interaction]
    tracking_methods = [WeakStrongBeamBeamMap]
    contracts = [ElementTrackingBackendConsistencyContract]
    analyses = [PlaceholderAnalysis]
    parameters = (
        kbb=ParamMeta(required=true, meaning="beam-beam kick coefficient"),
        klum=ParamMeta(default=1, meaning="luminosity scale"),
        beta=ParamMeta(meaning="strong-beam beta functions for the uncoupled convenience constructor"),
        alpha=ParamMeta(default=(0, 0), meaning="strong-beam alpha functions"),
        sigma=ParamMeta(meaning="strong-beam transverse sizes for the uncoupled convenience constructor"),
        covariance=ParamMeta(meaning="4 x 4 covariance in (x, px, y, py) order"),
        coupling=ParamMeta(meaning="optional XYCouplingSpec, XYCoupling, or symplectic 4 x 4 matrix"),
        center=ParamMeta(default=(0, 0, 0), meaning="strong-beam closed orbit center"),
        angle=ParamMeta(default=(0, 0, 0), meaning="strong-beam closed orbit angle"),
        curvature=ParamMeta(default=(0, 0, 0), meaning="strong-beam closed orbit curvature"),
        virtual_drift=ParamMeta(default=:hirata, meaning="named virtual-drift Hamiltonian or strategy"),
        tracking_method=ParamMeta(default=WeakStrongBeamBeamMap(), meaning="per-element tracking method"),
    )
    example = ThinStrongBeamSpec{Float64}(kbb=1e-4, beta=(1.0, 1.0), sigma=(1e-3, 1e-3))
    construction_help = "Friendly constructor: ThinStrongBeamSpec{T}(; kbb, klum=1, beta=nothing, alpha=(0,0), sigma=nothing, covariance=nothing, coupling=nothing, center=(0,0,0), angle=(0,0,0), curvature=(0,0,0), virtual_drift=:hirata, tracking_method=WeakStrongBeamBeamMap(), kwargs...). Supply beta/sigma or covariance; coupling transforms the uncoupled covariance."
end

@element_spec begin
    kind = :gaussian_strong_beam
    spec_type = ElementSpec{:gaussian_strong_beam}
    friendly_constructor = GaussianStrongBeamSpec
    runtime_type = GaussianStrongBeam
    description = "Flexible sliced Gaussian weak-strong beam-beam interaction specification."
    keywords = [:beam_beam, :nonlinear_interaction]
    tracking_methods = [WeakStrongBeamBeamMap]
    contracts = [ElementTrackingBackendConsistencyContract]
    analyses = [PlaceholderAnalysis]
    parameters = (
        thin=ParamMeta(required=true, meaning="base ThinStrongBeamSpec or ThinStrongBeam"),
        ns=ParamMeta(required=true, meaning="number of longitudinal slices"),
        slice_center=ParamMeta(meaning="explicit slice centers"),
        slice_weight=ParamMeta(meaning="explicit slice weights"),
        slice_hoffset=ParamMeta(meaning="explicit horizontal slice offsets"),
        slice_voffset=ParamMeta(meaning="explicit vertical slice offsets"),
        slice_pxoffset=ParamMeta(meaning="explicit horizontal-angle slice offsets"),
        slice_pyoffset=ParamMeta(meaning="explicit vertical-angle slice offsets"),
        sigz=ParamMeta(meaning="strong-beam longitudinal rms size; required unless explicit slice_center and slice_weight are supplied"),
        mean=ParamMeta(meaning="optional 6D Gaussian mean in (x, px, y, py, z, pz) order"),
        covariance=ParamMeta(meaning="optional 6 x 6 Gaussian covariance; slices use conditional transverse moments"),
        slice_method=ParamMeta(default=:equal_area, meaning=":equal_area or :equal_width"),
        slice_width=ParamMeta(meaning="slice width for :equal_width"),
        hvoffset=ParamMeta(meaning="optional Dict with dim, coef, frequency, harmonics"),
        tracking_method=ParamMeta(default=WeakStrongBeamBeamMap(), meaning="per-element tracking method"),
    )
    example = GaussianStrongBeamSpec{Float64}(thin=ThinStrongBeamSpec{Float64}(kbb=1e-4, beta=(1.0, 1.0), sigma=(1e-3, 1e-3)), ns=3, sigz=0.01)
    construction_help = "Friendly constructor: GaussianStrongBeamSpec{T}(; thin, ns, sigz=nothing, mean=nothing, covariance=nothing, slice_method=:equal_area, slice_width=nothing, slice_center=nothing, slice_weight=nothing, slice_hoffset=nothing, slice_voffset=nothing, slice_pxoffset=nothing, slice_pyoffset=nothing, hvoffset=nothing, tracking_method=WeakStrongBeamBeamMap(), kwargs...). A 6 x 6 covariance is conditioned on each longitudinal slice."
end

default_method(::Type{ElementSpec{:thin_strong_beam}}) = WeakStrongBeamBeamMap()
default_method(::Type{ElementSpec{:gaussian_strong_beam}}) = WeakStrongBeamBeamMap()
